// Auto-generated by scripts/fetch-osm-locations.ts on 2026-05-10.
// 589 locations pulled from OpenStreetMap and verified against
// Google Street View. Do not hand-edit — re-run the script to refresh.

import type { GameLocation } from "./types";

function sv(
  id: string,
  name: string,
  lat: number,
  lng: number,
  difficulty: 1 | 2 | 3,
  tags: string[],
): GameLocation {
  return {
    id,
    name,
    lat,
    lng,
    type: "streetview",
    streetviewPanoId: null,
    panoStoragePath: null,
    photoStoragePaths: null,
    difficulty,
    tags,
  };
}

export const GENERATED_LOCATIONS: GameLocation[] = [
  // place_of_worship · osm:way/218961783
  sv("360-church", "360 Church", 38.943443, -95.275491, 3, ["church"]),
  // cafe · osm:node/13207816905
  sv("7-brew", "7 Brew", 38.972457, -95.298473, 3, ["cafe"]),
  // restaurant · osm:node/2704141963
  sv("715-restaurant", "715 Restaurant", 38.970611, -95.235912, 3, ["restaurant"]),
  // restaurant · osm:node/11600417154
  sv("acapulco-mexican-grill", "Acapulco Mexican Grill", 38.955941, -95.305945, 3, ["restaurant"]),
  // university · osm:way/171147524
  sv("adams-alumni-center", "Adams Alumni Center", 38.960452, -95.242319, 3, ["misc"]),
  // cafe · osm:node/2702673101
  sv("aimee-s-coffeehouse", "Aimee's Coffeehouse", 38.964653, -95.235903, 3, ["cafe"]),
  // restaurant · osm:node/12845002489
  sv("aladdin-cafe", "Aladdin Cafe", 38.964834, -95.235903, 3, ["restaurant"]),
  // stadium · osm:way/87102555
  sv("allen-fieldhouse", "Allen Fieldhouse", 38.954612, -95.252377, 1, ["campus","sports","lawrence-staple"]),
  // alcohol · osm:node/2155519679
  sv("alvin-s-wine-spirits", "Alvin's Wine & Spirits", 38.972512, -95.289956, 3, ["misc"]),
  // sports_centre · osm:way/171147523
  sv("ambler-student-recreation-fitness-center", "Ambler Student Recreation Fitness Center", 38.952637, -95.248068, 3, ["sports"]),
  // university · osm:way/172577341
  sv("american-horse-hall", "American Horse Hall", 38.936872, -95.228923, 3, ["misc"]),
  // bank · osm:node/2865587088
  sv("ameriprise-financial", "Ameriprise Financial", 38.967035, -95.235901, 3, ["misc"]),
  // sports_centre · osm:way/87102557
  sv("anderson-family-strength-and-conditioning-center", "Anderson Family Strength and Conditioning Center", 38.954215, -95.255464, 3, ["sports"]),
  // sports_centre · osm:way/87102560
  sv("anschutz-sports-pavilion", "Anschutz Sports Pavilion", 38.953973, -95.255365, 3, ["sports"]),
  // bar · osm:node/8263027966
  sv("astros-billiards-and-bar", "Astros Billiards and Bar", 38.970987, -95.283079, 3, ["bar"]),
  // fast_food · osm:node/3877295452
  sv("auntie-em-s-deli", "Auntie Em's Deli", 38.94214, -95.308154, 3, ["restaurant"]),
  // university · osm:way/1106724465
  sv("baehr-audio-reader-center", "Baehr Audio-Reader Center", 38.964854, -95.250269, 3, ["misc"]),
  // university · osm:way/133940673
  sv("bailey-hall", "Bailey Hall", 38.957868, -95.246281, 3, ["misc"]),
  // bank · osm:node/10817128364
  sv("bank-of-america", "Bank of America", 38.972096, -95.303566, 3, ["misc"]),
  // alcohol · osm:node/9268995605
  sv("barley-s-liquor", "Barley's Liquor", 38.980301, -95.255976, 3, ["misc"]),
  // dormitory · osm:way/172183446
  sv("battenfeld-scholarship-hall", "Battenfeld Scholarship Hall", 38.957247, -95.243066, 3, ["dorm","campus"]),
  // hotel · osm:way/219402026
  sv("baymont", "Baymont", 38.97005, -95.259918, 3, ["hotel"]),
  // fitness_centre · osm:node/11632187703
  sv("be-moved-studio", "Be Moved Studio", 38.971254, -95.235538, 3, ["misc"]),
  // restaurant · osm:node/2157803710
  sv("bigg-s-barbecue", "Bigg's Barbecue", 38.939787, -95.261674, 3, ["restaurant"]),
  // restaurant · osm:node/2704141951
  sv("bigg-s-bbq", "Bigg's BBQ", 38.970518, -95.235912, 3, ["restaurant"]),
  // school · osm:way/274095143
  sv("bishop-seabury-academy", "Bishop Seabury Academy", 38.943191, -95.29322, 3, ["school"]),
  // pub · osm:node/1422313677
  sv("blade-timber-axe-throwing", "Blade & Timber Axe Throwing", 38.970335, -95.235912, 3, ["bar"]),
  // university · osm:way/134809488
  sv("blake-hall", "Blake Hall", 38.956276, -95.243588, 3, ["misc"]),
  // university · osm:way/172577344
  sv("blalock-hall", "Blalock Hall", 38.935895, -95.232506, 3, ["misc"]),
  // university · osm:way/172577350
  sv("blue-eagle-hall", "Blue Eagle Hall", 38.938102, -95.234223, 3, ["misc"]),
  // fitness_centre · osm:node/12111959867
  sv("blush-boot-camp", "Blush Boot Camp", 38.943655, -95.281884, 3, ["misc"]),
  // fitness_centre · osm:node/8946030377
  sv("body-boutique", "Body Boutique", 38.96674, -95.263294, 3, ["misc"]),
  // restaurant · osm:node/12687849440
  sv("bon-bon", "Bon Bon!", 38.969207, -95.22858, 3, ["restaurant"]),
  // museum · osm:way/171147512
  sv("booth-family-hall-of-athletics", "Booth Family Hall of Athletics", 38.954333, -95.25226, 3, ["museum"]),
  // school · osm:node/358633647
  sv("brackett-school", "Brackett School", 38.972315, -95.287915, 3, ["school"]),
  // monument · osm:node/3552640355
  sv("breezedale", "Breezedale", 38.942705, -95.235908, 3, ["historic"]),
  // place_of_worship · osm:way/218188093
  sv("bridgepointe-community-church", "BridgePointe Community Church", 38.931031, -95.241824, 3, ["church"]),
  // university · osm:way/48268207
  sv("bridwell-botany-research-laboratory-herbarium", "Bridwell Botany Research Laboratory Herbarium", 38.947811, -95.262814, 3, ["campus"]),
  // park · osm:way/1303396394
  sv("broken-arrow-park", "Broken Arrow Park", 38.930449, -95.240046, 3, ["park"]),
  // university · osm:way/115061491
  sv("budig-hall", "Budig Hall", 38.958013, -95.24965, 3, ["misc"]),
  // restaurant · osm:node/8927835341
  sv("buffalo-wild-wings", "Buffalo Wild Wings", 38.93471, -95.259731, 3, ["restaurant"]),
  // fast_food · osm:node/10069350601
  sv("burger-king", "Burger King", 38.939155, -95.261217, 3, ["restaurant"]),
  // restaurant · osm:node/11600417151
  sv("burgers-by-biggs", "Burgers by Biggs", 38.956155, -95.305741, 3, ["restaurant"]),
  // department_store · osm:node/8019760614
  sv("burlington", "Burlington", 38.926295, -95.258935, 3, ["shopping"]),
  // place_of_worship · osm:way/217760379
  sv("calvary-church-of-god-in-christ", "Calvary Church of God in Christ", 38.971526, -95.245815, 3, ["church"]),
  // place_of_worship · osm:way/218188091
  sv("calvary-lawrence", "Calvary Lawrence", 38.931544, -95.242317, 3, ["church"]),
  // bank · osm:node/11839070466
  sv("capitol-federal", "Capitol Federal", 38.970616, -95.304043, 3, ["misc"]),
  // university · osm:way/612774799
  sv("capitol-federal-hall", "Capitol Federal Hall", 38.953697, -95.250156, 3, ["misc"]),
  // university · osm:way/115429561
  sv("carruth-o-leary-hall", "Carruth - O'Leary Hall", 38.961101, -95.25097, 3, ["misc"]),
  // restaurant · osm:node/12459739742
  sv("cascada-la-golondrina", "Cascada La Golondrina", 38.943231, -95.211736, 3, ["restaurant"]),
  // place_of_worship · osm:way/388802810
  sv("centenary-united-methodist-church", "Centenary United Methodist Church", 38.976709, -95.231232, 3, ["church"]),
  // park · osm:way/965274027
  sv("centennial-park", "Centennial Park", 38.97027, -95.264514, 3, ["park"]),
  // school · osm:way/1192550965
  sv("centennial-school", "Centennial School", 38.944658, -95.244182, 3, ["school"]),
  // university · osm:way/649611383
  sv("center-for-design-research", "Center for Design Research", 38.956951, -95.271132, 3, ["misc"]),
  // university · osm:way/636959563
  sv("central-district-utility-plant", "Central District Utility Plant", 38.954925, -95.256065, 3, ["misc"]),
  // bank · osm:node/11000915057
  sv("central-national-bank", "Central National Bank", 38.923499, -95.257752, 3, ["misc"]),
  // place_of_worship · osm:way/219102236
  sv("chabad-at-ku", "Chabad at KU", 38.950077, -95.24892, 3, ["church"]),
  // university · osm:way/134801176
  sv("chalmers-hall-art-and-design", "Chalmers Hall (Art and Design)", 38.957751, -95.250597, 3, ["misc"]),
  // university · osm:way/266413486
  sv("chamney-barn", "Chamney Barn", 38.956953, -95.270062, 3, ["misc"]),
  // university · osm:way/266413487
  sv("chamney-house", "Chamney House", 38.956951, -95.270786, 3, ["misc"]),
  // fast_food · osm:node/13226632828
  sv("champs-chicken", "Champs Chicken", 38.942405, -95.240462, 3, ["restaurant"]),
  // park · osm:way/219241191
  sv("chaparral-park", "Chaparral Park", 38.935389, -95.220172, 3, ["park"]),
  // alcohol · osm:node/9069050766
  sv("cheers-liquor", "Cheers Liquor", 38.973347, -95.251792, 3, ["misc"]),
  // artwork · osm:node/8958914466
  sv("chesty-lion", "Chesty Lion", 38.950111, -95.243283, 3, ["statue"]),
  // fast_food · osm:node/12535261170
  sv("chick-fil-a", "Chick-fil-A", 38.959047, -95.24338, 3, ["restaurant"]),
  // park · osm:way/1289797507
  sv("chief-jim-mcswain-park", "Chief Jim McSwain Park", 38.949314, -95.223451, 3, ["park"]),
  // university · osm:way/650340117
  sv("chiller-building", "Chiller Building", 38.954151, -95.248944, 3, ["misc"]),
  // restaurant · osm:node/2796310182
  sv("china-house", "China House", 38.970267, -95.306044, 3, ["restaurant"]),
  // fast_food · osm:node/2703830985
  sv("chipotle", "Chipotle", 38.967035, -95.235901, 3, ["restaurant"]),
  // fast_food · osm:node/9691047532
  sv("chipotle-2", "Chipotle", 38.972509, -95.28949, 3, ["restaurant"]),
  // place_of_worship · osm:way/175354166
  sv("christ-community-church", "Christ Community Church", 38.964286, -95.277795, 3, ["church"]),
  // place_of_worship · osm:way/823270774
  sv("christ-covenant-church", "Christ Covenant Church", 38.964601, -95.263112, 3, ["church"]),
  // place_of_worship · osm:node/358647190
  sv("church-of-god", "Church of God", 38.976937, -95.217026, 3, ["church"]),
  // place_of_worship · osm:node/358647156
  sv("church-of-god-holiness", "Church of God Holiness", 38.983325, -95.230859, 3, ["church"]),
  // townhall · osm:way/49826210
  sv("city-hall", "City Hall", 38.97314, -95.235655, 3, ["misc"]),
  // alcohol · osm:node/8952427527
  sv("city-wine-market", "City Wine Market", 38.970286, -95.305345, 3, ["misc"]),
  // bakery · osm:node/12676800244
  sv("cleo-leo-on-elm-st", "Cleo & Leo On Elm St", 38.976975, -95.233444, 3, ["misc"]),
  // park · osm:way/1042072788
  sv("clinton-park", "Clinton Park", 38.974788, -95.24647, 3, ["park"]),
  // park · osm:way/43725066
  sv("clinton-state-park", "Clinton State Park", 38.937911, -95.367111, 3, ["park"]),
  // park · osm:node/358634665
  sv("clinton-wildlife-area", "Clinton Wildlife Area", 38.921169, -95.328849, 3, ["park"]),
  // sports_centre · osm:way/172577355
  sv("coffin-sports-complex", "Coffin Sports Complex", 38.939265, -95.228356, 3, ["sports"]),
  // hotel · osm:way/1395644222
  sv("comfort-inn-suites", "Comfort Inn & Suites", 38.981518, -95.259797, 3, ["hotel"]),
  // fitness_centre · osm:node/12312485946
  sv("common-ground-soma-yoga", "Common Ground Soma Yoga", 38.959987, -95.235166, 3, ["misc"]),
  // place_of_worship · osm:way/670497105
  sv("connect-church", "Connect Church", 38.927156, -95.27682, 3, ["church"]),
  // park · osm:way/48762415
  sv("constant-park", "Constant Park", 38.974097, -95.23942, 3, ["park"]),
  // university · osm:way/219360482
  sv("continuing-education", "Continuing Education", 38.955747, -95.28274, 3, ["campus"]),
  // dormitory · osm:way/666991842
  sv("corbin-residence-hall", "Corbin Residence Hall", 38.964529, -95.241448, 3, ["dorm","campus"]),
  // school · osm:way/978872588
  sv("cordley-elementary-school", "Cordley Elementary School", 38.950836, -95.238043, 3, ["school"]),
  // sports_centre · osm:node/2863476921
  sv("core-form-studio", "Core:form Studio", 38.96769, -95.230655, 3, ["sports"]),
  // alcohol · osm:node/8232821774
  sv("cork-barrel", "Cork & Barrel", 38.942109, -95.256507, 3, ["misc"]),
  // place_of_worship · osm:way/1188393601
  sv("cornerstone-community-church", "Cornerstone Community Church", 38.939223, -95.203341, 3, ["church"]),
  // place_of_worship · osm:way/219358737
  sv("corpus-christi-catholic-church", "Corpus Christi Catholic Church", 38.95703, -95.324906, 3, ["church"]),
  // school · osm:way/1043624421
  sv("corpus-christi-catholic-school", "Corpus Christi Catholic School", 38.958262, -95.323085, 3, ["school"]),
  // restaurant · osm:node/2864344829
  sv("cosmos-indian-store", "Cosmos Indian Store", 38.97007, -95.235802, 3, ["restaurant"]),
  // hotel · osm:way/1290504052
  sv("country-inn-suites", "Country Inn & Suites", 38.942993, -95.207975, 3, ["hotel"]),
  // theatre · osm:way/134843212
  sv("crafton-preyer-theatre", "Crafton-Preyer Theatre", 38.956496, -95.251966, 3, ["venue"]),
  // university · osm:way/180877350
  sv("crawford-community-center", "Crawford Community Center", 38.95852, -95.241704, 3, ["misc"]),
  // pub · osm:node/8946030386
  sv("crimson-and-brews", "Crimson and Brews", 38.967266, -95.263295, 3, ["bar"]),
  // books · osm:node/13101061210
  sv("crimson-corner", "Crimson Corner", 38.955685, -95.258789, 3, ["misc"]),
  // restaurant · osm:node/12681620363
  sv("culinaria", "Culinaria", 38.967947, -95.230437, 3, ["restaurant"]),
  // university · osm:way/172577358
  sv("curtis-hall", "Curtis Hall", 38.93735, -95.23222, 3, ["misc"]),
  // bicycle · osm:node/11505260185
  sv("cycle-works", "Cycle Works", 38.94502, -95.280153, 3, ["misc"]),
  // sports_centre · osm:node/12963704841
  sv("d-bat-baseball-and-softball-academy", "D-BAT Baseball and Softball Academy", 38.939886, -95.199116, 3, ["sports"]),
  // park · osm:way/1157535000
  sv("dad-perry-park", "\"Dad\" Perry Park", 38.961715, -95.287152, 3, ["park"]),
  // university · osm:way/382989555
  sv("daisy-hill-commons", "Daisy Hill Commons", 38.954626, -95.258868, 3, ["misc"]),
  // place_of_worship · osm:way/171147514
  sv("danforth-chapel", "Danforth Chapel", 38.957741, -95.243164, 3, ["church"]),
  // stadium · osm:way/1422566786
  sv("david-booth-kansas-memorial-stadium", "David Booth Kansas Memorial Stadium", 38.962869, -95.24636, 1, ["campus","sports","lawrence-staple"]),
  // hotel · osm:way/219402152
  sv("days-inn", "Days Inn", 38.970502, -95.260411, 3, ["hotel"]),
  // university · osm:way/634020684
  sv("debruce-center", "Debruce Center", 38.955234, -95.252261, 3, ["misc"]),
  // school · osm:way/1254394594
  sv("deerfield-elementary-school", "Deerfield Elementary School", 38.982817, -95.27143, 3, ["school"]),
  // park · osm:way/186585315
  sv("deerfield-park", "Deerfield Park", 38.982298, -95.274807, 3, ["park"]),
  // university · osm:way/134809492
  sv("dole-human-development-center", "Dole Human Development Center", 38.955394, -95.246687, 3, ["misc"]),
  // hotel · osm:way/136226587
  sv("doubletree", "DoubleTree", 38.979974, -95.257525, 3, ["hotel"]),
  // yes · osm:way/44932340
  sv("douglas-county-courthouse", "Douglas County Courthouse", 38.963418, -95.2359, 3, ["historic"]),
  // courthouse · osm:way/174710510
  sv("douglas-county-judicial-and-law-enforcement-cent", "Douglas County Judicial and Law Enforcement Center", 38.963031, -95.234386, 3, ["misc"]),
  // memorial · osm:node/13059024727
  sv("douglas-county-memorial-of-honor", "Douglas County Memorial of Honor", 38.978216, -95.234434, 3, ["historic"]),
  // dormitory · osm:way/171147515
  sv("douthart-scholarship-hall", "Douthart Scholarship Hall", 38.958426, -95.241704, 3, ["dorm","campus"]),
  // dormitory · osm:way/612791517
  sv("downs-residence-hall", "Downs Residence Hall", 38.951283, -95.253559, 3, ["dorm","campus"]),
  // university · osm:node/12688085268
  sv("east-hills-ku-architecture-warehouse", "East Hills KU Architecture Warehouse", 38.943096, -95.18424, 3, ["campus"]),
  // sports_centre · osm:way/171260530
  sv("east-lawrence-recreation-center", "East Lawrence Recreation Center", 38.956467, -95.220092, 3, ["sports"]),
  // place_of_worship · osm:way/219402044
  sv("eastside-bible-fellowship", "Eastside Bible Fellowship", 38.957004, -95.224061, 3, ["church"]),
  // community_centre · osm:way/214424644
  sv("ecumenical-campus-ministries", "Ecumenical Campus Ministries", 38.961385, -95.242388, 3, ["misc"]),
  // park · osm:way/1301018519
  sv("edgewood-park", "Edgewood Park", 38.954376, -95.219374, 3, ["park"]),
  // university · osm:way/986027615
  sv("ehs-storage-facility", "EHS Storage Facility", 38.949223, -95.264647, 3, ["misc"]),
  // dormitory · osm:way/452929195
  sv("ellsworth-residential-hall", "Ellsworth Residential Hall", 38.952747, -95.259197, 3, ["dorm","campus"]),
  // bar · osm:node/12684674496
  sv("elmo-s-tavern", "Elmo's Tavern", 38.977823, -95.228266, 3, ["bar"]),
  // bar · osm:node/4408871790
  sv("empire-pubcade-and-venue", "Empire Pubcade and Venue", 38.967573, -95.262548, 3, ["bar"]),
  // restaurant · osm:node/2703785711
  sv("encore-cafe", "Encore Cafe", 38.965286, -95.235902, 3, ["restaurant"]),
  // university · osm:way/645138776
  sv("engineering-structural-testing-student-project-f", "Engineering Structural Testing & Student Project Facility", 38.946046, -95.267946, 3, ["misc"]),
  // cafe · osm:node/11173898035
  sv("espurresso-cat-cafe", "Espurresso Cat Cafe", 38.965012, -95.235903, 3, ["cafe"]),
  // alcohol · osm:node/9758116131
  sv("everest-liquors", "Everest Liquors", 38.958191, -95.278281, 3, ["misc"]),
  // fitness_centre · osm:node/9054851002
  sv("evolution-athletics", "Evolution Athletics", 38.926437, -95.256507, 3, ["misc"]),
  // university · osm:way/986027616
  sv("facilities-storage-building", "Facilities Storage Building", 38.951973, -95.271928, 3, ["misc"]),
  // university · osm:way/986027617
  sv("facilities-storage-building-2", "Facilities Storage Building", 38.954937, -95.27174, 3, ["misc"]),
  // place_of_worship · osm:way/219358942
  sv("family-church", "Family Church", 38.95186, -95.334585, 3, ["church"]),
  // place_of_worship · osm:node/358647155
  sv("fellowship-baptist-church", "Fellowship Baptist Church", 38.978353, -95.223971, 3, ["church"]),
  // fast_food · osm:node/8193050004
  sv("firehouse-subs", "Firehouse Subs", 38.928601, -95.258472, 3, ["restaurant"]),
  // place_of_worship · osm:way/1035285506
  sv("first-baptist-church", "First Baptist Church", 38.960111, -95.278927, 3, ["church"]),
  // place_of_worship · osm:way/174714180
  sv("first-christian-church", "First Christian Church", 38.965245, -95.237681, 3, ["church"]),
  // place_of_worship · osm:way/218961704
  sv("first-presbyterian-church", "First Presbyterian Church", 38.941603, -95.265177, 3, ["church"]),
  // place_of_worship · osm:way/219195901
  sv("first-regular-missionary-baptist-church", "First Regular Missionary Baptist Church", 38.953881, -95.237085, 3, ["church"]),
  // place_of_worship · osm:way/1053443707
  sv("first-southern-baptist-church", "First Southern Baptist Church", 38.972553, -95.294707, 3, ["church"]),
  // place_of_worship · osm:way/174714177
  sv("first-united-methodist-church", "First United Methodist Church", 38.966076, -95.23653, 3, ["church"]),
  // restaurant · osm:node/8201033758
  sv("first-watch", "First Watch", 38.937117, -95.260204, 3, ["restaurant"]),
  // bar · osm:node/2863476926
  sv("five-bar", "Five Bar", 38.965784, -95.236045, 3, ["bar"]),
  // fast_food · osm:node/8193050002
  sv("five-guys", "Five Guys", 38.928487, -95.259288, 3, ["restaurant"]),
  // university · osm:way/48158394
  sv("foley-hall", "Foley Hall", 38.948076, -95.263336, 3, ["campus"]),
  // bakery · osm:node/9576594815
  sv("formosa-bakery", "Formosa Bakery", 38.937413, -95.262916, 3, ["misc"]),
  // university · osm:way/133940391
  sv("fraser-hall", "Fraser Hall", 38.957096, -95.24381, 3, ["misc"]),
  // place_of_worship · osm:node/12068510351
  sv("free-city-church", "Free City Church", 38.95759, -95.235885, 3, ["church"]),
  // place_of_worship · osm:way/175354167
  sv("free-state-church", "Free State Church", 38.967065, -95.281127, 3, ["church"]),
  // school · osm:way/886608989
  sv("free-state-high-school", "Free State High School", 38.976347, -95.304642, 3, ["school"]),
  // fast_food · osm:node/9691047535
  sv("fruitful-acai-bowls", "Fruitful Acai Bowls", 38.972641, -95.289056, 3, ["restaurant"]),
  // building · osm:way/217605421
  sv("general-john-roberts-castle", "General John Roberts Castle", 38.95965, -95.236519, 3, ["historic"]),
  // restaurant · osm:node/2703830988
  sv("genovese", "Genovese", 38.965999, -95.235902, 3, ["restaurant"]),
  // dormitory · osm:way/180851105
  sv("gertrude-sellards-pearson-residence-hall", "Gertrude Sellards Pearson Residence Hall", 38.964922, -95.241743, 3, ["dorm","campus"]),
  // alcohol · osm:node/3877284003
  sv("glass-house-liquor", "Glass House Liquor", 38.942173, -95.307957, 3, ["misc"]),
  // cafe · osm:node/2864344830
  sv("global-cafe", "Global Cafe", 38.968512, -95.235901, 3, ["cafe"]),
  // restaurant · osm:node/5771171005
  sv("globe-indian-food", "Globe Indian Food", 38.972386, -95.235909, 3, ["restaurant"]),
  // restaurant · osm:node/8952427522
  sv("glory-days-pizza", "Glory Days Pizza", 38.970267, -95.306147, 3, ["restaurant"]),
  // place_of_worship · osm:way/587878293
  sv("good-shepherd-lutheran-church", "Good Shepherd Lutheran Church", 38.943601, -95.297837, 3, ["church"]),
  // fast_food · osm:node/9758116130
  sv("goodcents-subs", "Goodcents Subs", 38.958063, -95.278161, 3, ["restaurant"]),
  // dormitory · osm:way/171147516
  sv("grace-pearson-scholarship-hall", "Grace Pearson Scholarship Hall", 38.958798, -95.241703, 3, ["dorm","campus"]),
  // place_of_worship · osm:way/814303186
  sv("grace-presbyterian-church", "Grace Presbyterian Church", 38.990086, -95.278911, 3, ["church"]),
  // university · osm:way/634020682
  sv("gray-little-hall", "Gray-Little Hall", 38.955658, -95.255474, 3, ["misc"]),
  // university · osm:way/171728623
  sv("green-hall", "Green Hall", 38.956497, -95.254668, 3, ["misc"]),
  // park · osm:way/218192416
  sv("green-meadows-park", "Green Meadows Park", 38.933693, -95.282218, 3, ["park"]),
  // university · osm:way/48268209
  sv("greenhouse", "Greenhouse", 38.947882, -95.263533, 3, ["misc"]),
  // restaurant · osm:node/2864344833
  sv("grinders-lfk", "Grinders LFK", 38.969928, -95.234703, 3, ["restaurant"]),
  // building · osm:way/219637507
  sv("grover-barn-underground-railroad-station", "Grover Barn Underground Railroad Station", 38.941504, -95.269423, 3, ["historic"]),
  // university · osm:way/171147517
  sv("hall-center-for-the-humanities", "Hall Center for the Humanities", 38.955287, -95.245718, 3, ["misc"]),
  // hotel · osm:way/218982366
  sv("hampton-inn", "Hampton Inn", 38.972781, -95.264003, 3, ["hotel"]),
  // park · osm:way/1184370525
  sv("hand-park", "Hand Park", 38.939435, -95.222141, 3, ["park"]),
  // alcohol · osm:node/8946030361
  sv("happy-hour-liquor-and-tobacco", "Happy Hour Liquor and Tobacco", 38.967335, -95.26113, 3, ["misc"]),
  // pub · osm:node/4691206589
  sv("harolds", "Harolds", 38.966749, -95.235901, 3, ["bar"]),
  // alcohol · osm:node/11721524356
  sv("harper-liquor", "Harper Liquor", 38.943414, -95.213836, 3, ["misc"]),
  // dormitory · osm:way/172603554
  sv("hashinger-residence-hall", "Hashinger Residence Hall", 38.954127, -95.259158, 3, ["dorm","campus"]),
  // place_of_worship · osm:way/218961787
  sv("haskell-catholic-campus-center", "Haskell Catholic Campus Center", 38.942494, -95.232732, 3, ["church"]),
  // museum · osm:way/172577364
  sv("haskell-cultural-center-and-museum", "Haskell Cultural Center and Museum", 38.940328, -95.233187, 3, ["museum"]),
  // library · osm:way/172577367
  sv("haskell-library", "Haskell Library", 38.939153, -95.233815, 3, ["library"]),
  // place_of_worship · osm:way/219641350
  sv("haskell-light", "Haskell Light", 38.940977, -95.234054, 3, ["church"]),
  // park · osm:way/176566361
  sv("haskell-rail-trail", "Haskell Rail-Trail", 38.937303, -95.228699, 3, ["park"]),
  // stadium · osm:way/865203093
  sv("haskell-stadium", "Haskell Stadium", 38.940015, -95.230611, 3, ["sports"]),
  // university · osm:way/115429560
  sv("haworth-hall", "Haworth Hall", 38.955916, -95.248546, 3, ["misc"]),
  // cafe · osm:node/2713414567
  sv("henry-s-pub-and-coffee-house", "Henry's pub and coffee house", 38.969262, -95.235306, 3, ["cafe"]),
  // university · osm:way/172577379
  sv("hiawatha-hall", "Hiawatha Hall", 38.939516, -95.231092, 3, ["misc"]),
  // university · osm:way/134860443
  sv("higuchi-hall", "Higuchi Hall", 38.946268, -95.262587, 3, ["campus"]),
  // university · osm:way/645138775
  sv("hill-engineering-research-and-development-center", "Hill Engineering Research and Development Center", 38.946213, -95.268, 3, ["misc"]),
  // school · osm:way/964846548
  sv("hillcrest-elementary-school", "Hillcrest Elementary School", 38.965433, -95.259134, 3, ["school"]),
  // school · osm:way/443537455
  sv("hilltop-child-development-center", "Hilltop Child Development Center", 38.953964, -95.255856, 3, ["school"]),
  // park · osm:way/1301670904
  sv("hobbs-park", "Hobbs Park", 38.964751, -95.227774, 3, ["park"]),
  // restaurant · osm:node/13318583746
  sv("hog-wild-pit-bar-b-q", "Hog Wild Pit Bar-B-Q", 38.942873, -95.253395, 3, ["restaurant"]),
  // stadium · osm:way/663885905
  sv("hoglund-ballpark", "Hoglund Ballpark", 38.952892, -95.252759, 3, ["sports"]),
  // park · osm:way/909862598
  sv("holcom-park", "Holcom Park", 38.93782, -95.266343, 3, ["park"]),
  // sports_centre · osm:way/174381022
  sv("holcom-park-recreation-center", "Holcom Park Recreation Center", 38.935562, -95.268225, 3, ["sports"]),
  // hotel · osm:way/218961778
  sv("holiday-inn-express", "Holiday Inn Express", 38.921595, -95.261169, 3, ["hotel"]),
  // bar · osm:node/2702673109
  sv("hookah-lounge", "HOOKAH LOUNGE", 38.964742, -95.235903, 3, ["bar"]),
  // stadium · osm:way/87102558
  sv("horejsi-family-athletics-center", "Horejsi Family Athletics Center", 38.953707, -95.253326, 3, ["sports"]),
  // restaurant · osm:node/8201040239
  sv("huhot", "HuHot", 38.937104, -95.261618, 3, ["restaurant"]),
  // fast_food · osm:node/12470569179
  sv("hummus-republic", "Hummus Republic", 38.928504, -95.258479, 3, ["restaurant"]),
  // place_of_worship · osm:way/219360592
  sv("immanuel-lutheran-church", "Immanuel Lutheran Church", 38.957523, -95.260476, 3, ["church"]),
  // restaurant · osm:node/2157803726
  sv("india-palace", "India Palace", 38.965647, -95.234973, 3, ["restaurant"]),
  // place_of_worship · osm:way/219641329
  sv("indian-avenue-baptist-church", "Indian Avenue Baptist Church", 38.940295, -95.233637, 3, ["church"]),
  // restaurant · osm:node/622199061
  sv("ingredient", "Ingredient", 38.96565, -95.236162, 3, ["restaurant"]),
  // place_of_worship · osm:way/219102256
  sv("islamic-center-of-lawrence", "Islamic Center of Lawrence", 38.949532, -95.251276, 3, ["church"]),
  // restaurant · osm:node/2702635299
  sv("it-s-brothers-bar-grill", "It's Brothers Bar & Grill", 38.963418, -95.2359, 3, ["restaurant"]),
  // cafe · osm:node/8952427523
  sv("j-s-coffee", "J&S Coffee", 38.970268, -95.30593, 3, ["cafe"]),
  // restaurant · osm:node/624082927
  sv("j-wilson-s", "J. Wilson's", 38.970267, -95.306385, 3, ["restaurant"]),
  // restaurant · osm:node/2729898995
  sv("jade-garden", "Jade Garden", 38.958633, -95.27828, 3, ["restaurant"]),
  // restaurant · osm:node/8019760608
  sv("jason-s-deli", "Jason's Deli", 38.925813, -95.259843, 3, ["restaurant"]),
  // dormitory · osm:way/172603556
  sv("jayhawk-towers-apartments", "Jayhawk Towers Apartments", 38.957043, -95.255772, 3, ["dorm","campus"]),
  // university · osm:way/1351742004
  sv("jayhawk-welcome-center", "Jayhawk Welcome Center", 38.96046, -95.242271, 3, ["misc"]),
  // fitness_centre · osm:node/9758116134
  sv("jazzercise", "Jazzercise", 38.958991, -95.27828, 3, ["misc"]),
  // restaurant · osm:node/11600417157
  sv("jefferson-s", "Jefferson's", 38.955325, -95.30652, 3, ["restaurant"]),
  // restaurant · osm:node/2704141953
  sv("jefferson-s-lawrence", "Jefferson's Lawrence", 38.969712, -95.235911, 3, ["restaurant"]),
  // fast_food · osm:node/2157803638
  sv("jersey-mike-s-subs", "Jersey Mike's Subs", 38.972049, -95.305126, 3, ["restaurant"]),
  // place_of_worship · osm:node/8840318636
  sv("jesus-community", "Jesus Community", 38.928992, -95.264257, 3, ["church"]),
  // university · osm:way/172577380
  sv("jim-thorpe-hall", "Jim Thorpe Hall", 38.937629, -95.230312, 3, ["misc"]),
  // fast_food · osm:node/4691206590
  sv("jimmy-john-s", "Jimmy John's", 38.966543, -95.235901, 3, ["restaurant"]),
  // fast_food · osm:node/8263027967
  sv("jimmy-john-s-2", "Jimmy John's", 38.970941, -95.282844, 3, ["restaurant"]),
  // park · osm:way/274202325
  sv("john-taylor-park", "John Taylor Park", 38.975767, -95.224271, 3, ["park"]),
  // restaurant · osm:node/2156885375
  sv("johnny-s-tavern", "Johnny's Tavern", 38.969356, -95.308082, 2, ["bar","north-lawrence","lawrence-staple"]),
  // alcohol · osm:node/12111959866
  sv("joker-liquor-smokes", "Joker Liquor & Smokes", 38.943922, -95.281603, 3, ["misc"]),
  // university · osm:way/171728626
  sv("joseph-r-pearson-hall", "Joseph R Pearson Hall", 38.962431, -95.250866, 3, ["misc"]),
  // dormitory · osm:way/171147518
  sv("k-k-amini-scholarship-hall", "K.K. Amini Scholarship Hall", 38.95889, -95.241703, 3, ["dorm","campus"]),
  // university · osm:way/134806458
  sv("kansas-union", "Kansas Union", 38.959382, -95.243212, 3, ["misc"]),
  // fitness_centre · osm:node/11733082143
  sv("kaw-valley-crossfit", "Kaw Valley CrossFit", 38.940855, -95.220727, 3, ["misc"]),
  // library · osm:way/171172696
  sv("kenneth-spencer-research-library", "Kenneth Spencer Research Library", 38.959416, -95.247818, 3, ["library"]),
  // place_of_worship · osm:way/281215197
  sv("kingdom-hall-of-jehovah-s-witnesses", "Kingdom Hall of Jehovah's Witnesses", 38.950384, -95.212904, 3, ["church"]),
  // university · osm:way/172577381
  sv("kiva-hall", "Kiva Hall", 38.938102, -95.234223, 3, ["misc"]),
  // place_of_worship · osm:way/1197844398
  sv("korean-presbyterian-church-of-lawrence", "Korean Presbyterian Church of Lawrence", 38.98259, -95.228532, 3, ["church"]),
  // memorial · osm:node/366762570
  sv("korean-war-memorial", "Korean War Memorial", 38.958971, -95.249807, 3, ["historic"]),
  // dormitory · osm:way/180849826
  sv("krehbiel-scholarship-hall", "Krehbiel Scholarship Hall", 38.959692, -95.241167, 3, ["dorm","campus"]),
  // university · osm:way/32548230
  sv("ku-endowment-building", "KU Endowment Building", 38.951796, -95.26295, 3, ["misc"]),
  // sports_centre · osm:way/691738782
  sv("ku-football-indoor-practice-facility", "KU Football Indoor Practice Facility", 38.962947, -95.247861, 3, ["sports"]),
  // place_of_worship · osm:node/12169333184
  sv("ku-hillel", "KU Hillel", 38.962702, -95.242906, 3, ["church"]),
  // university · osm:way/47009157
  sv("kurata-thermodynamics-laboratories", "Kurata Thermodynamics Laboratories", 38.949323, -95.264853, 3, ["misc"]),
  // cafe · osm:node/2495639979
  sv("la-prima-tazza", "La Prima Tazza", 38.97155, -95.235911, 3, ["cafe"]),
  // restaurant · osm:node/12684643791
  sv("la-tropicana", "La Tropicana", 38.977821, -95.229601, 3, ["restaurant"]),
  // university · osm:way/219360575
  sv("landscape-and-construction-building", "Landscape and Construction Building", 38.954151, -95.272074, 3, ["campus"]),
  // fitness_centre · osm:node/11600417155
  sv("lava-yoga", "Lava Yoga", 38.955797, -95.306083, 3, ["misc"]),
  // arts_centre · osm:way/44931605
  sv("lawrence-arts-center", "Lawrence Arts Center", 38.966487, -95.234137, 3, ["misc"]),
  // place_of_worship · osm:way/219357733
  sv("lawrence-baptist-temple", "Lawrence Baptist Temple", 38.928121, -95.275633, 3, ["church"]),
  // sports_centre · osm:node/5910583819
  sv("lawrence-barbell-club", "Lawrence Barbell Club", 38.961557, -95.225443, 3, ["sports"]),
  // pub · osm:node/2864130116
  sv("lawrence-beer-company", "Lawrence Beer Company", 38.968402, -95.228906, 3, ["bar"]),
  // pub · osm:node/11600546499
  sv("lawrence-beer-company-2", "Lawrence Beer Company", 38.956628, -95.305074, 3, ["bar"]),
  // place_of_worship · osm:way/205581075
  sv("lawrence-bible-chapel", "Lawrence Bible Chapel", 38.97526, -95.288313, 3, ["church"]),
  // place_of_worship · osm:way/304615086
  sv("lawrence-chinese-evangelical-church", "Lawrence Chinese Evangelical Church", 38.944409, -95.219468, 3, ["church"]),
  // place_of_worship · osm:way/218982336
  sv("lawrence-church-of-christ", "Lawrence Church of Christ", 38.984258, -95.251149, 3, ["church"]),
  // school · osm:way/1303822192
  sv("lawrence-college-and-career-center", "Lawrence College and Career Center", 38.931099, -95.220905, 3, ["school"]),
  // sports_centre · osm:way/214550400
  sv("lawrence-community-building", "Lawrence Community Building", 38.963369, -95.236516, 3, ["sports"]),
  // fire_station · osm:node/366763353
  sv("lawrence-douglas-county-fire-and-medical-station", "Lawrence Douglas County Fire and Medical Station 1", 38.969391, -95.237901, 3, ["misc"]),
  // fire_station · osm:node/366763365
  sv("lawrence-douglas-county-fire-and-medical-station-2", "Lawrence Douglas County Fire and Medical Station 6", 38.979997, -95.248549, 3, ["misc"]),
  // place_of_worship · osm:way/1254751021
  sv("lawrence-heights-christian-church", "Lawrence Heights Christian Church", 38.985099, -95.263178, 3, ["church"]),
  // place_of_worship · osm:way/267777150
  sv("lawrence-indian-united-methodist-church", "Lawrence Indian United Methodist Church", 38.946898, -95.224128, 3, ["church"]),
  // sports_centre · osm:way/219358955
  sv("lawrence-indoor-aquatic-center", "Lawrence Indoor Aquatic Center", 38.976396, -95.30312, 3, ["sports"]),
  // place_of_worship · osm:way/219360579
  sv("lawrence-jewish-community-congregation", "Lawrence Jewish Community Congregation", 38.966958, -95.259135, 3, ["church"]),
  // alcohol · osm:node/13415031891
  sv("lawrence-liquors", "Lawrence Liquors", 38.993342, -95.25965, 3, ["misc"]),
  // hospital · osm:way/218978291
  sv("lawrence-memorial-hospital", "Lawrence Memorial Hospital", 38.978977, -95.249517, 3, ["hospital"]),
  // courthouse · osm:node/6321137385
  sv("lawrence-municipal-court", "Lawrence Municipal Court", 38.972977, -95.234814, 3, ["misc"]),
  // sports_centre · osm:way/1004815176
  sv("lawrence-outdoor-aquatic-center", "Lawrence Outdoor Aquatic Center", 38.96995, -95.239436, 3, ["sports"]),
  // library · osm:way/51126839
  sv("lawrence-public-library", "Lawrence Public Library", 38.970817, -95.237628, 3, ["library"]),
  // university · osm:way/490445913
  sv("learned-engineering-expansion-phase-2", "Learned Engineering Expansion Phase 2", 38.957939, -95.254774, 3, ["misc"]),
  // university · osm:way/171728639
  sv("learned-hall", "Learned Hall", 38.957775, -95.253792, 3, ["misc"]),
  // butcher · osm:node/8946030351
  sv("leeway-butcher-shop", "Leeway Butcher Shop", 38.966817, -95.261507, 3, ["misc"]),
  // restaurant · osm:node/4644982327
  sv("leeway-franks", "Leeway Franks", 38.966833, -95.261391, 3, ["restaurant"]),
  // bar · osm:node/6321136684
  sv("leroy-s-tavern", "Leroy's Tavern", 38.970352, -95.23495, 3, ["bar"]),
  // dormitory · osm:way/172603572
  sv("lewis-residence-hall", "Lewis Residence Hall", 38.955304, -95.258245, 3, ["dorm","campus"]),
  // cinema · osm:node/2863476928
  sv("liberty-hall", "Liberty Hall", 38.971441, -95.235914, 1, ["mass-st","venue","lawrence-staple"]),
  // school · osm:way/1007155568
  sv("liberty-memorial-central-middle-school", "Liberty Memorial Central Middle School", 38.958168, -95.234083, 3, ["school"]),
  // university · osm:way/219360617
  sv("library-annex", "Library Annex", 38.950671, -95.271999, 3, ["misc"]),
  // theatre · osm:way/390538796
  sv("lied-center-of-kansas", "Lied Center of Kansas", 38.954422, -95.262803, 3, ["venue"]),
  // fitness_centre · osm:node/12818519498
  sv("lifting-for-life", "Lifting for Life", 38.967878, -95.232382, 3, ["misc"]),
  // restaurant · osm:node/2283112830
  sv("limestone-pizza-kitchen-bar", "Limestone Pizza•Kitchen•Bar", 38.968774, -95.235902, 3, ["restaurant"]),
  // school · osm:node/358633693
  sv("lincoln-school", "Lincoln School", 38.976675, -95.224269, 3, ["school"]),
  // university · osm:way/644674632
  sv("lindley-hall", "Lindley Hall", 38.958433, -95.25115, 3, ["misc"]),
  // university · osm:way/134806459
  sv("lippincott-hall", "Lippincott Hall", 38.958096, -95.243992, 3, ["misc"]),
  // fast_food · osm:node/8403852378
  sv("little-caesars", "Little Caesars", 38.94287, -95.253963, 3, ["restaurant"]),
  // fast_food · osm:node/11836485314
  sv("little-caesars-2", "Little Caesars", 38.971297, -95.272853, 3, ["restaurant"]),
  // university · osm:way/172603576
  sv("little-nations-academic-center", "Little Nations Academic Center", 38.937767, -95.228544, 3, ["misc"]),
  // restaurant · osm:node/8403852379
  sv("little-saigon-cafe", "Little Saigon Cafe", 38.942872, -95.253623, 3, ["restaurant"]),
  // bar · osm:node/5771171004
  sv("local", "Local", 38.972476, -95.235913, 3, ["bar"]),
  // restaurant · osm:node/604970998
  sv("local-burger", "Local Burger", 38.970534, -95.237123, 3, ["restaurant"]),
  // attraction · osm:node/9701849245
  sv("locomotive-1073", "Locomotive #1073", 38.97231, -95.238272, 3, ["misc"]),
  // restaurant · osm:node/13726686040
  sv("longboards-wraps-and-bowls", "Longboards Wraps and Bowls", 38.936563, -95.260206, 3, ["restaurant"]),
  // music · osm:node/2863476929
  sv("love-garden-sounds", "Love Garden Sounds", 38.968453, -95.235856, 3, ["misc"]),
  // bar · osm:node/2865336605
  sv("lucia", "Lucia", 38.964924, -95.235903, 3, ["bar"]),
  // restaurant · osm:node/10254956310
  sv("lucky-seb-s-dumpling-bar-and-grill", "Lucky Seb's Dumpling Bar and Grill", 38.944442, -95.259631, 3, ["restaurant"]),
  // park · osm:way/220471287
  sv("ludlam-park", "Ludlam Park", 38.968641, -95.268607, 3, ["park"]),
  // park · osm:way/49228645
  sv("lyons-park", "Lyons Park", 38.980994, -95.222814, 3, ["park"]),
  // restaurant · osm:node/2864344834
  sv("maceli-s", "Maceli's", 38.964526, -95.234688, 3, ["restaurant"]),
  // artwork · osm:node/1435565526
  sv("mackomics-studio", "MacKomics Studio", 38.944329, -95.239414, 3, ["statue"]),
  // university · osm:way/687430570
  sv("maintenance-entry", "Maintenance Entry", 38.957544, -95.25036, 3, ["misc"]),
  // university · osm:way/266413488
  sv("maintenance-surplus-property", "Maintenance & Surplus Property", 38.956675, -95.264166, 3, ["misc"]),
  // dormitory · osm:way/171147519
  sv("margaret-amini-scholarship-hall", "Margaret Amini Scholarship Hall", 38.959256, -95.241703, 3, ["dorm","campus"]),
  // park · osm:way/165122723
  sv("marvin-grove", "Marvin Grove", 38.96043, -95.247199, 3, ["park"]),
  // university · osm:way/115061488
  sv("marvin-hall", "Marvin Hall", 38.958241, -95.25024, 3, ["misc"]),
  // university · osm:way/134802492
  sv("marvin-studios", "Marvin Studios", 38.957736, -95.250113, 3, ["misc"]),
  // alcohol · osm:node/4414188992
  sv("mass-beverage", "Mass Beverage", 38.927284, -95.263481, 3, ["misc"]),
  // restaurant · osm:node/2704141961
  sv("mass-street-fish-house-raw-bar", "Mass Street Fish House & Raw Bar", 38.970518, -95.235912, 3, ["restaurant"]),
  // bakery · osm:node/2704141956
  sv("mass-street-sweet-shoppe", "Mass Street Sweet Shoppe", 38.970272, -95.235989, 3, ["misc"]),
  // university · osm:way/219360538
  sv("max-kade-center", "Max Kade Center", 38.964101, -95.250853, 3, ["misc"]),
  // restaurant · osm:node/4414198083
  sv("mcalister-s-deli", "McAlister's Deli", 38.934882, -95.261399, 3, ["restaurant"]),
  // university · osm:way/134860444
  sv("mccollum-laboratories", "McCollum Laboratories", 38.946926, -95.261605, 3, ["campus"]),
  // restaurant · osm:node/9713230078
  sv("mediterranean-market-cafe", "Mediterranean Market & Cafe", 38.957251, -95.277574, 3, ["restaurant"]),
  // memorial · osm:way/115429559
  sv("memorial-campanile-carillon", "Memorial Campanile & Carillon", 38.960003, -95.246937, 1, ["campus","lawrence-staple"]),
  // restaurant · osm:node/2864344835
  sv("merchants", "Merchants", 38.969392, -95.235686, 3, ["restaurant"]),
  // place_of_worship · osm:node/8823449464
  sv("mercy-seat-tabernacle", "Mercy Seat Tabernacle", 38.940856, -95.2436, 3, ["church"]),
  // bank · osm:node/11021349574
  sv("meritrust-credit-union", "Meritrust Credit Union", 38.97094, -95.310844, 3, ["misc"]),
  // university · osm:way/115429563
  sv("military-science-building", "Military Science Building", 38.95684, -95.249794, 3, ["misc"]),
  // dormitory · osm:way/172183451
  sv("miller-scholarship-hall", "Miller Scholarship Hall", 38.956446, -95.242793, 3, ["dorm","campus"]),
  // cafe · osm:node/12687865017
  sv("milton-s-cafe", "Milton's Cafe", 38.967522, -95.235028, 3, ["cafe"]),
  // restaurant · osm:node/2864344836
  sv("minsky-s-pizza-cafe-bar", "Minsky's Pizza Cafe & Bar", 38.96618, -95.235901, 3, ["restaurant"]),
  // university · osm:way/48839152
  sv("moore-hall-hambleton-hall", "Moore Hall/Hambleton Hall", 38.94956, -95.262259, 3, ["misc"]),
  // restaurant · osm:node/12459739738
  sv("moriki-sushi", "Moriki Sushi", 38.94323, -95.211143, 3, ["restaurant"]),
  // place_of_worship · osm:way/1086070521
  sv("morning-star-church", "Morning Star Church", 38.997222, -95.316473, 3, ["church"]),
  // restaurant · osm:node/4425413056
  sv("morningstar-s-new-york-pizza", "Morningstar's New York Pizza", 38.970656, -95.309076, 3, ["restaurant"]),
  // cafe · osm:node/2463905706
  sv("mortar-pestle-caf", "Mortar & Pestle Café", 38.948734, -95.264549, 3, ["cafe"]),
  // artwork · osm:node/9244353449
  sv("moses", "Moses", 38.959672, -95.242652, 3, ["statue"]),
  // cafe · osm:node/13226632829
  sv("mother-earth-coffee", "Mother Earth Coffee", 38.942058, -95.241134, 3, ["cafe"]),
  // restaurant · osm:node/2283112837
  sv("mr-brew-s-taphouse", "Mr. Brew's Taphouse", 38.968884, -95.234701, 3, ["restaurant"]),
  // pub · osm:node/11132928711
  sv("mr-brew-s-taphouse-2", "Mr. Brew's Taphouse", 38.925818, -95.259618, 3, ["bar"]),
  // university · osm:way/47987521
  sv("multidisciplinary-research-building", "Multidisciplinary Research Building", 38.947465, -95.265712, 3, ["campus"]),
  // bakery · osm:node/3697198378
  sv("munchers-bakery", "Munchers Bakery", 38.966985, -95.262393, 3, ["misc"]),
  // house · osm:way/221054645
  sv("murphy-bromelsick-house", "Murphy-Bromelsick House", 38.965399, -95.227775, 3, ["historic"]),
  // university · osm:way/134841590
  sv("murphy-hall", "Murphy Hall", 38.955929, -95.250869, 3, ["misc"]),
  // restaurant · osm:node/8823402304
  sv("nagoya-japanese-cuisine", "Nagoya Japanese Cuisine", 38.94085, -95.243002, 3, ["restaurant"]),
  // dormitory · osm:way/180771023
  sv("naismith-hall", "Naismith Hall", 38.950764, -95.250806, 3, ["dorm","campus"]),
  // museum · osm:way/134806460
  sv("natural-history-museum", "Natural History Museum", 38.958748, -95.243532, 3, ["museum"]),
  // university · osm:way/712549528
  sv("navarre-hall", "Navarre Hall", 38.939035, -95.230225, 3, ["misc"]),
  // place_of_worship · osm:way/219360468
  sv("new-hope-fellowship", "New Hope Fellowship", 38.957457, -95.279118, 3, ["church"]),
  // school · osm:way/1187938851
  sv("new-york-elementary-school", "New York Elementary School", 38.966559, -95.231227, 3, ["school"]),
  // fitness_centre · osm:node/8823402319
  sv("next-level-rising", "Next Level Rising", 38.941223, -95.243621, 3, ["misc"]),
  // university · osm:way/32548189
  sv("nichols-hall", "Nichols Hall", 38.952401, -95.26452, 3, ["misc"]),
  // place_of_worship · osm:way/219195816
  sv("ninth-street-missionary-baptist-church", "Ninth Street Missionary Baptist Church", 38.967512, -95.240927, 3, ["church"]),
  // restaurant · osm:node/627134693
  sv("noodles-co-noodle-company", "Noodles & Co.;Noodle Company", 38.96939, -95.236182, 3, ["restaurant"]),
  // place_of_worship · osm:way/1197830257
  sv("north-lawrence-christian-church", "North Lawrence Christian Church", 38.976979, -95.224562, 3, ["church"]),
  // university · osm:way/172603592
  sv("north-winnemucca-hall", "North Winnemucca Hall", 38.935427, -95.231926, 3, ["misc"]),
  // bar · osm:node/12684643792
  sv("northside-social", "Northside Social", 38.977822, -95.229361, 3, ["bar"]),
  // university · osm:way/172603593
  sv("nunemaker-center", "Nunemaker Center", 38.955867, -95.257523, 3, ["misc"]),
  // fitness_centre · osm:node/11021349581
  sv("ohm-fitness", "OHM Fitness", 38.970657, -95.309301, 3, ["misc"]),
  // university · osm:way/46965693
  sv("old-schoolhouse", "Old Schoolhouse", 38.942772, -95.2613, 3, ["misc"]),
  // restaurant · osm:node/13095054603
  sv("olive-garden", "Olive Garden", 38.946336, -95.259869, 3, ["restaurant"]),
  // fitness_centre · osm:node/8840637857
  sv("omni-fitness", "Omni Fitness", 38.92841, -95.265552, 3, ["misc"]),
  // sports_centre · osm:node/2864228442
  sv("omni-method-gym", "Omni Method Gym", 38.967011, -95.227069, 3, ["sports"]),
  // fitness_centre · osm:node/10822657112
  sv("orangetheory-fitness", "Orangetheory Fitness", 38.972133, -95.307738, 3, ["misc"]),
  // place_of_worship · osm:way/686352965
  sv("oread-center", "Oread Center", 38.966992, -95.24522, 1, ["campus","lawrence-staple"]),
  // place_of_worship · osm:way/219652144
  sv("oread-friends-meeting", "Oread Friends Meeting", 38.962103, -95.225447, 1, ["campus","lawrence-staple"]),
  // university · osm:way/172577387
  sv("osceola-keokuk-hall", "Osceola - Keokuk Hall", 38.942009, -95.23156, 3, ["misc"]),
  // dormitory · osm:way/382989556
  sv("oswald-residence-hall", "Oswald Residence Hall", 38.954279, -95.259994, 3, ["dorm","campus"]),
  // park · osm:way/220725308
  sv("overlook-park", "Overlook Park", 38.939622, -95.340887, 3, ["park"]),
  // sports_centre · osm:way/964093515
  sv("padgett-family-training-center", "Padgett Family Training Center", 38.952279, -95.253419, 3, ["sports"]),
  // fast_food · osm:node/8265684016
  sv("panda-express", "Panda Express", 38.924212, -95.259843, 3, ["restaurant"]),
  // fast_food · osm:node/9704445410
  sv("panera-bread", "Panera Bread", 38.943049, -95.243128, 3, ["restaurant"]),
  // restaurant · osm:node/2703953851
  sv("papa-keno-s", "Papa Keno's", 38.967979, -95.2359, 3, ["restaurant"]),
  // restaurant · osm:node/2702704761
  sv("papa-keno-s-pizzeria", "Papa Keno's Pizzeria", 38.964307, -95.235904, 3, ["restaurant"]),
  // fast_food · osm:node/11021349573
  sv("papa-murphy-s", "Papa Murphy's", 38.97086, -95.310302, 3, ["restaurant"]),
  // park · osm:way/220681080
  sv("park-hill-park-1", "Park Hill Park #1", 38.936762, -95.239737, 3, ["park"]),
  // park · osm:way/220681079
  sv("park-hill-park-2", "Park Hill Park #2", 38.938762, -95.237958, 3, ["park"]),
  // park · osm:way/220681152
  sv("park-hill-park-3", "Park Hill Park #3", 38.940532, -95.237739, 3, ["park"]),
  // university · osm:way/172577388
  sv("parker-hall", "Parker Hall", 38.935983, -95.231258, 3, ["misc"]),
  // park · osm:way/1300381902
  sv("parnell-park", "Parnell Park", 38.95583, -95.226898, 3, ["park"]),
  // park · osm:way/218189559
  sv("pat-dawson-billings-nature-area", "Pat Dawson Billings Nature Area", 38.932937, -95.292554, 3, ["park"]),
  // place_of_worship · osm:node/358647127
  sv("peace-mennonite-church", "Peace Mennonite Church", 38.980554, -95.225252, 3, ["church"]),
  // dormitory · osm:way/60862870
  sv("pearson-scholarship-hall", "Pearson Scholarship Hall", 38.957237, -95.242188, 3, ["dorm","campus"]),
  // restaurant · osm:node/2703830993
  sv("pepperjax-grill", "Pepperjax Grill", 38.966749, -95.235901, 3, ["restaurant"]),
  // fast_food · osm:node/11639950116
  sv("petra2go", "Petra2Go", 38.94214, -95.308154, 3, ["restaurant"]),
  // university · osm:way/134860446
  sv("pharmaceutical-chemistry-laboratories", "Pharmaceutical Chemistry Laboratories", 38.947438, -95.262737, 3, ["campus"]),
  // memorial · osm:node/9287201527
  sv("phog-allen", "Phog Allen", 38.954351, -95.2521, 3, ["historic"]),
  // restaurant · osm:node/2864373490
  sv("pickleman-s-gourmet-cafe", "Pickleman's Gourmet Cafe", 38.968603, -95.235901, 3, ["restaurant"]),
  // restaurant · osm:node/9279492844
  sv("pickleman-s-gourmet-cafe-2", "Pickleman's Gourmet Cafe", 38.943795, -95.281769, 3, ["restaurant"]),
  // school · osm:way/1042072796
  sv("pinckney-school", "Pinckney School", 38.973741, -95.245805, 3, ["school"]),
  // fast_food · osm:node/2702673113
  sv("pita-pit", "Pita Pit", 38.965198, -95.235902, 3, ["restaurant"]),
  // restaurant · osm:node/10998479907
  sv("pizza-hut", "Pizza Hut", 38.970987, -95.301952, 3, ["restaurant"]),
  // fast_food · osm:node/8232821775
  sv("pizza-shuttle", "Pizza Shuttle", 38.940823, -95.243469, 3, ["restaurant"]),
  // fitness_centre · osm:node/4414173283
  sv("planet-fitness", "Planet Fitness", 38.93783, -95.261692, 3, ["misc"]),
  // university · osm:way/172577389
  sv("pontiac-hall", "Pontiac Hall", 38.936835, -95.231714, 3, ["misc"]),
  // gallery · osm:node/2864461473
  sv("prairie-hills-art-gallery", "Prairie Hills Art Gallery", 38.967809, -95.2359, 3, ["misc"]),
  // school · osm:way/1364135459
  sv("prairie-moon-waldorf-school", "Prairie Moon Waldorf School", 39.008846, -95.205487, 3, ["school"]),
  // school · osm:way/1161591024
  sv("prairie-park-elementary-school", "Prairie Park Elementary School", 38.934241, -95.20958, 3, ["school"]),
  // museum · osm:way/173108121
  sv("prairie-park-nature-center", "Prairie Park Nature Center", 38.933124, -95.215798, 3, ["museum"]),
  // place_of_worship · osm:way/171260537
  sv("praise-temple-church-of-god-in-christ", "Praise Temple Church of God in Christ", 38.971091, -95.232976, 3, ["church"]),
  // cafe · osm:node/8201033759
  sv("presotea", "Presotea", 38.937207, -95.260203, 3, ["cafe"]),
  // university · osm:way/171728621
  sv("price-computing-center", "Price Computing Center", 38.954872, -95.246233, 3, ["misc"]),
  // fitness_centre · osm:node/8952427526
  sv("pure-barre", "Pure Barre", 38.970269, -95.305476, 3, ["misc"]),
  // restaurant · osm:node/2702704763
  sv("pyramid-pizza", "Pyramid Pizza", 38.964567, -95.235903, 3, ["restaurant"]),
  // school · osm:way/1240681354
  sv("quail-run-elementary-school", "Quail Run Elementary School", 38.962315, -95.302357, 3, ["school"]),
  // park · osm:way/470436873
  sv("quail-run-park", "Quail Run Park", 38.962965, -95.304603, 3, ["park"]),
  // hotel · osm:way/218961904
  sv("quality-inn-suites", "Quality Inn & Suites", 38.942167, -95.261817, 3, ["hotel"]),
  // park · osm:way/219521080
  sv("quarry-park", "Quarry Park", 38.960073, -95.262052, 3, ["park"]),
  // restaurant · osm:node/2864373491
  sv("raman-bowls", "Raman Bowls", 38.965482, -95.235295, 3, ["restaurant"]),
  // restaurant · osm:node/12249157643
  sv("ramen-bowls", "Ramen Bowls", 38.967525, -95.23452, 3, ["restaurant"]),
  // bar · osm:node/2864344837
  sv("red-lyon-tavern", "Red Lyon Tavern", 38.965907, -95.235902, 3, ["bar"]),
  // place_of_worship · osm:way/174399127
  sv("redeemer-lutheran-church", "Redeemer Lutheran Church", 38.935012, -95.268869, 3, ["church"]),
  // place_of_worship · osm:way/174836259
  sv("redemption-hill-church", "Redemption Hill Church", 38.944292, -95.244484, 3, ["church"]),
  // cinema · osm:way/218961899
  sv("regal-southwind", "Regal Southwind", 38.921533, -95.263382, 3, ["venue"]),
  // artwork · osm:node/4962188230
  sv("relay-race", "Relay Race", 38.976164, -95.304641, 3, ["statue"]),
  // bar · osm:node/2863476932
  sv("replay-lounge", "Replay Lounge", 38.965813, -95.235902, 2, ["mass-st","bar"]),
  // place_of_worship · osm:way/205716559
  sv("rev-city-church", "Rev City Church", 38.969066, -95.30696, 3, ["church"]),
  // music · osm:node/10127189505
  sv("richard-s-music-co", "Richard's Music Co.", 38.969389, -95.23511, 3, ["misc"]),
  // bar · osm:node/9005721834
  sv("rick-s-place", "Rick's Place", 38.967776, -95.24495, 3, ["bar"]),
  // dormitory · osm:way/180772287
  sv("rieger-scholarship-hall", "Rieger Scholarship Hall", 38.95896, -95.241162, 3, ["dorm","campus"]),
  // university · osm:way/644674636
  sv("ritchie-hall", "Ritchie Hall", 38.958296, -95.252114, 3, ["misc"]),
  // place_of_worship · osm:way/218974602
  sv("river-city-church", "River City Church", 38.928922, -95.273411, 3, ["church"]),
  // university · osm:way/172183459
  sv("robert-j-dole-institute-of-politics", "Robert J. Dole Institute of Politics", 38.955876, -95.264937, 3, ["misc"]),
  // university · osm:way/134809490
  sv("robinson-health-and-physical-education-center", "Robinson Health and Physical Education Center", 38.955089, -95.249707, 3, ["misc"]),
  // park · osm:way/48268333
  sv("robinson-park", "Robinson Park", 38.973599, -95.236897, 3, ["park"]),
  // sports_centre · osm:way/1342319768
  sv("rock-chalk-park", "Rock Chalk Park", 38.981179, -95.32859, 3, ["sports"]),
  // university · osm:way/172577392
  sv("roe-cloud-hall", "Roe Cloud Hall", 38.936845, -95.233835, 3, ["misc"]),
  // university · osm:way/172577393
  sv("ross-hall", "Ross Hall", 38.937092, -95.23123, 3, ["misc"]),
  // alcohol · osm:node/9738977400
  sv("roy-s-wine-spirits", "Roy's Wine & Spirits", 38.96998, -95.308083, 3, ["misc"]),
  // restaurant · osm:node/613633882
  sv("rudy-s-pizzeria", "Rudy's Pizzeria", 38.971084, -95.235478, 3, ["restaurant"]),
  // university · osm:way/214424676
  sv("sabatini-multicultural-resource-center", "Sabatini Multicultural Resource Center", 38.959888, -95.243098, 3, ["misc"]),
  // school · osm:way/174714179
  sv("saint-john-catholic-school", "Saint John Catholic School", 38.961273, -95.23825, 3, ["school"]),
  // place_of_worship · osm:way/174714181
  sv("saint-john-the-evangelist-catholic-church", "Saint John the Evangelist Catholic Church", 38.96064, -95.238254, 3, ["church"]),
  // place_of_worship · osm:way/174405205
  sv("saint-luke-african-methodist-episcopal-church", "Saint Luke African Methodist Episcopal Church", 38.967517, -95.230855, 3, ["church"]),
  // place_of_worship · osm:way/219358881
  sv("saint-margaret-s-episcopal-church", "Saint Margaret's Episcopal Church", 38.971575, -95.323171, 3, ["church"]),
  // place_of_worship · osm:way/681537161
  sv("saint-nicholas-orthodox-church", "Saint Nicholas Orthodox Church", 38.960978, -95.260426, 3, ["church"]),
  // park · osm:way/368060001
  sv("sandra-j-shaw-community-health-park", "Sandra J. Shaw Community Health Park", 38.981796, -95.245297, 3, ["park"]),
  // restaurant · osm:node/8952427525
  sv("sandwich-bowl", "Sandwich Bowl", 38.970269, -95.30559, 3, ["restaurant"]),
  // fast_food · osm:node/10069350602
  sv("sbarro", "Sbarro", 38.938824, -95.261243, 3, ["restaurant"]),
  // university · osm:way/238568717
  sv("school-of-pharmacy-building", "School of Pharmacy Building", 38.948758, -95.264403, 3, ["misc"]),
  // school · osm:way/914288647
  sv("schwegler-elementary-school", "Schwegler Elementary School", 38.94454, -95.257282, 3, ["school"]),
  // university · osm:way/172577396
  sv("seattle-hall", "Seattle Hall", 38.936295, -95.230217, 3, ["misc"]),
  // place_of_worship · osm:node/358647515
  sv("second-christian-church", "Second Christian Church", 38.961533, -95.232373, 3, ["church"]),
  // dormitory · osm:way/382989557
  sv("self-residence-hall", "Self Residence Hall", 38.955551, -95.259325, 3, ["dorm","campus"]),
  // dormitory · osm:way/172183455
  sv("sellards-scholarship-hall", "Sellards Scholarship Hall", 38.956489, -95.241587, 3, ["dorm","campus"]),
  // university · osm:way/172577398
  sv("sequoyah-hall", "Sequoyah Hall", 38.938426, -95.231073, 3, ["misc"]),
  // restaurant · osm:node/8702611630
  sv("set-em-up-jack-s", "Set'em Up Jack's", 38.943231, -95.212207, 3, ["restaurant"]),
  // sports_centre · osm:way/87102553
  sv("shafford-holland-strength-center", "Shafford - Holland Strength Center", 38.954849, -95.254473, 3, ["sports"]),
  // bar · osm:node/11600417153
  sv("shenago-lounge", "Shenago Lounge", 38.956082, -95.305811, 3, ["bar"]),
  // sports_centre · osm:way/240322831
  sv("shenk-recreational-sports-complex", "Shenk Recreational Sports Complex", 38.944833, -95.262483, 3, ["sports"]),
  // university · osm:way/240313098
  sv("shenkel-structural-biology-center", "Shenkel Structural Biology Center", 38.946952, -95.263464, 3, ["misc"]),
  // university · osm:way/172183470
  sv("shop-facility", "Shop Facility", 38.95322, -95.272086, 3, ["misc"]),
  // bank · osm:node/13126424872
  sv("silver-lake-bank", "Silver Lake Bank", 38.972116, -95.235898, 3, ["misc"]),
  // university · osm:way/49662840
  sv("simons-biosciences-research-laboratories", "Simons Biosciences Research Laboratories", 38.947819, -95.261828, 3, ["campus"]),
  // restaurant · osm:node/4425413055
  sv("six-mile-chop-house", "Six Mile Chop House", 38.970991, -95.309463, 3, ["restaurant"]),
  // university · osm:way/644674637
  sv("slawson-hall", "Slawson Hall", 38.957594, -95.252108, 3, ["misc"]),
  // restaurant · osm:node/12477143395
  sv("slice-of-history", "Slice of History", 38.962343, -95.242906, 3, ["restaurant"]),
  // university · osm:way/49666834
  sv("smissman-research-laboratories", "Smissman Research Laboratories", 38.946874, -95.263262, 3, ["campus"]),
  // fast_food · osm:node/10822657111
  sv("smoothie-king", "Smoothie King", 38.972133, -95.307625, 3, ["restaurant"]),
  // university · osm:way/115061504
  sv("snow-hall", "Snow Hall", 38.958981, -95.249107, 3, ["misc"]),
  // university · osm:way/172603595
  sv("south-winnemucca-hall", "South Winnemucca Hall", 38.934533, -95.232697, 3, ["misc"]),
  // place_of_worship · osm:way/218191273
  sv("southside-church-of-christ", "Southside Church of Christ", 38.938441, -95.248711, 3, ["church"]),
  // school · osm:way/890020566
  sv("southwest-middle-school", "Southwest Middle School", 38.93954, -95.300046, 3, ["school"]),
  // library · osm:way/171728634
  sv("spahr-engineering-library", "Spahr Engineering Library", 38.95734, -95.25276, 3, ["library"]),
  // museum · osm:way/134806461
  sv("spencer-museum-of-art", "Spencer Museum of Art", 38.959666, -95.244328, 3, ["museum"]),
  // restaurant · osm:node/6296774241
  sv("spin-pizza", "Spin! Pizza", 38.973164, -95.307711, 3, ["restaurant"]),
  // university · osm:way/134809491
  sv("spooner-hall", "Spooner Hall", 38.958496, -95.243006, 3, ["misc"]),
  // park · osm:way/367711082
  sv("sports-pavilion-lawrence", "Sports Pavilion Lawrence", 38.982697, -95.330235, 3, ["park"]),
  // sports_centre · osm:way/365632293
  sv("sports-pavillion-lawrence", "Sports Pavillion Lawrence", 38.982772, -95.328536, 3, ["sports"]),
  // hotel · osm:node/12137010449
  sv("springhill-suites", "SpringHill Suites", 38.972312, -95.233555, 3, ["hotel"]),
  // place_of_worship · osm:way/219360528
  sv("st-lawrence-catholic-campus-center", "St. Lawrence Catholic Campus Center", 38.958292, -95.25699, 3, ["church"]),
  // cafe · osm:node/4693971291
  sv("starbucks", "Starbucks", 38.972263, -95.271865, 3, ["cafe"]),
  // cafe · osm:node/9033413680
  sv("starbucks-2", "Starbucks", 38.955009, -95.254525, 3, ["cafe"]),
  // cafe · osm:node/9279492841
  sv("starbucks-3", "Starbucks", 38.944029, -95.280598, 3, ["cafe"]),
  // cafe · osm:node/10817128362
  sv("starbucks-4", "Starbucks", 38.972097, -95.303287, 3, ["cafe"]),
  // cafe · osm:node/11166210352
  sv("starbucks-5", "Starbucks", 38.925879, -95.263418, 3, ["cafe"]),
  // cafe · osm:node/11632187701
  sv("starbucks-6", "Starbucks", 38.971254, -95.236084, 3, ["cafe"]),
  // cafe · osm:node/12439958478
  sv("starbucks-7", "Starbucks", 38.952161, -95.23553, 3, ["cafe"]),
  // cafe · osm:node/13244884574
  sv("starbucks-8", "Starbucks", 38.944833, -95.262483, 3, ["cafe"]),
  // university · osm:way/133920167
  sv("stauffer-flint-hall", "Stauffer - Flint Hall", 38.956924, -95.246497, 3, ["misc"]),
  // dormitory · osm:way/32974142
  sv("stephenson-scholarship-hall", "Stephenson Scholarship Hall", 38.957779, -95.242132, 3, ["dorm","campus"]),
  // hotel · osm:way/220471014
  sv("stone-hill-hotel", "Stone Hill Hotel", 38.978111, -95.326246, 3, ["hotel"]),
  // place_of_worship · osm:node/11021349583
  sv("story-hill-church", "Story Hill Church", 38.970692, -95.309404, 3, ["church"]),
  // university · osm:way/115429558
  sv("strong-hall", "Strong Hall", 38.958383, -95.247763, 3, ["misc"]),
  // fast_food · osm:node/2157803631
  sv("subway", "Subway", 38.955472, -95.306385, 3, ["restaurant"]),
  // fast_food · osm:node/4414188991
  sv("subway-2", "Subway", 38.92732, -95.263376, 3, ["restaurant"]),
  // fast_food · osm:node/8702611631
  sv("subway-3", "Subway", 38.943232, -95.211621, 3, ["restaurant"]),
  // fast_food · osm:node/9130906745
  sv("subway-4", "Subway", 38.973419, -95.254321, 3, ["restaurant"]),
  // fast_food · osm:node/9691047533
  sv("subway-5", "Subway", 38.972587, -95.28912, 3, ["restaurant"]),
  // university · osm:way/219517834
  sv("sudler-annex", "Sudler Annex", 38.964253, -95.250225, 3, ["misc"]),
  // university · osm:way/133920211
  sv("summerfield-hall", "Summerfield Hall", 38.955781, -95.249665, 3, ["misc"]),
  // school · osm:way/890020567
  sv("sunflower-elementary-school", "Sunflower Elementary School", 38.935355, -95.299647, 3, ["school"]),
  // bicycle · osm:node/1739082603
  sv("sunflower-outdoor-bike-shop", "Sunflower Outdoor & Bike Shop", 38.969132, -95.235904, 3, ["misc"]),
  // school · osm:way/966349632
  sv("sunset-hill-elementary-school", "Sunset Hill Elementary School", 38.967082, -95.269683, 3, ["school"]),
  // restaurant · osm:node/9704445407
  sv("sushi-station", "Sushi Station", 38.943413, -95.242477, 3, ["restaurant"]),
  // restaurant · osm:node/10815683038
  sv("t-loft", "t.Loft", 38.972049, -95.305126, 3, ["restaurant"]),
  // fitness_centre · osm:node/9713230083
  sv("tallgrass-training-and-wellness", "Tallgrass Training and Wellness", 38.957252, -95.277459, 3, ["misc"]),
  // university · osm:way/172577399
  sv("tecumseh-hall", "Tecumseh Hall", 38.939244, -95.231089, 3, ["misc"]),
  // dormitory · osm:way/172603621
  sv("templin-residence-hall", "Templin Residence Hall", 38.956386, -95.25838, 3, ["dorm","campus"]),
  // restaurant · osm:node/2704163298
  sv("ten-restaurant", "TEN Restaurant", 38.970977, -95.235917, 3, ["restaurant"]),
  // alcohol · osm:node/11726414552
  sv("ten-star-liquor", "Ten Star Liquor", 38.942433, -95.224555, 3, ["misc"]),
  // fast_food · osm:node/2703953883
  sv("terrabonne", "Terrabonne", 38.96772, -95.2359, 3, ["restaurant"]),
  // restaurant · osm:node/8026877220
  sv("texas-roadhouse", "Texas Roadhouse", 38.941334, -95.261522, 3, ["restaurant"]),
  // restaurant · osm:node/9704445409
  sv("thai-diner", "Thai Diner", 38.943414, -95.242717, 3, ["restaurant"]),
  // restaurant · osm:node/8263027969
  sv("thai-siam", "Thai-Siam", 38.970941, -95.282844, 3, ["restaurant"]),
  // place_of_worship · osm:node/9279492853
  sv("the-anchor-church", "The Anchor Church", 38.943114, -95.293276, 3, ["church"]),
  // restaurant · osm:node/10115609008
  sv("the-basil-leaf-cafe", "The Basil Leaf Cafe", 38.969389, -95.236333, 3, ["restaurant"]),
  // restaurant · osm:node/4425413057
  sv("the-big-biscuit", "The Big Biscuit", 38.970268, -95.305815, 3, ["restaurant"]),
  // bar · osm:node/2863476934
  sv("the-bottleneck", "The Bottleneck", 38.969846, -95.236534, 2, ["bar","venue","lawrence-staple"]),
  // pub · osm:node/2863458123
  sv("the-bourgeois-pig", "The Bourgeois Pig", 38.967601, -95.23532, 3, ["bar"]),
  // university · osm:way/634020680
  sv("the-burge-union", "The Burge Union", 38.955089, -95.254941, 3, ["misc"]),
  // fast_food · osm:node/2283112833
  sv("the-burger-stand-at-the-casbah", "The Burger Stand at The Casbah", 38.96939, -95.236182, 3, ["restaurant"]),
  // place_of_worship · osm:way/175354165
  sv("the-church-of-jesus-christ-of-latter-day-saints", "The Church of Jesus Christ of Latter-day Saints", 38.967562, -95.284353, 3, ["church"]),
  // place_of_worship · osm:way/279546656
  sv("the-church-of-jesus-christ-of-latter-day-saints-", "The Church of Jesus Christ of Latter-Day Saints Institute of Religion", 38.950021, -95.255154, 3, ["church"]),
  // books · osm:node/1739082593
  sv("the-dusty-bookshelf", "The Dusty Bookshelf", 38.970886, -95.235916, 3, ["misc"]),
  // restaurant · osm:node/2704141962
  sv("the-dynamite-saloon", "The Dynamite Saloon", 38.970425, -95.235912, 3, ["restaurant"]),
  // bar · osm:node/10127189506
  sv("the-eighth-street-tap-room", "The Eighth Street Tap Room", 38.969388, -95.234884, 3, ["bar"]),
  // hotel · osm:node/2863476935
  sv("the-eldridge-hotel", "The Eldridge Hotel", 38.971085, -95.236542, 2, ["mass-st","lawrence-staple"]),
  // hotel · osm:node/10127152391
  sv("the-eldrige-extended", "The Eldrige Extended", 38.969385, -95.237508, 3, ["hotel"]),
  // fast_food · osm:node/11140300330
  sv("the-fresh-mediterranean-company", "The Fresh Mediterranean Company", 38.942994, -95.247763, 3, ["restaurant"]),
  // theatre · osm:node/2865488197
  sv("the-granada", "The Granada", 38.964742, -95.235903, 2, ["mass-st","venue","lawrence-staple"]),
  // park · osm:way/161955948
  sv("the-japansese-friendship-garden", "The Japansese Friendship Garden", 38.964211, -95.236521, 3, ["park"]),
  // cafe · osm:node/1726310300
  sv("the-java-break", "The Java Break", 38.971255, -95.234962, 3, ["cafe"]),
  // artwork · osm:node/12255867919
  sv("the-jayhawk-nest", "The Jayhawk Nest", 38.959267, -95.243268, 3, ["statue"]),
  // theatre · osm:node/2283112834
  sv("the-jayhawker-at-the-eldridge", "The Jayhawker at The Eldridge", 38.971254, -95.236202, 2, ["mass-st","lawrence-staple"]),
  // bicycle · osm:node/4687271419
  sv("the-lawrence-re-cyclery", "The Lawrence Re-Cyclery", 38.976976, -95.233888, 3, ["misc"]),
  // restaurant · osm:node/2283112835
  sv("the-mad-greek", "The Mad Greek", 38.967128, -95.235901, 3, ["restaurant"]),
  // cafe · osm:node/12684657221
  sv("the-nostalgia-room", "The Nostalgia Room", 38.967517, -95.231808, 3, ["cafe"]),
  // hotel · osm:way/136228941
  sv("the-oread", "The Oread", 38.962343, -95.242906, 1, ["campus","lawrence-staple"]),
  // books · osm:node/2704009971
  sv("the-raven", "The Raven", 38.968948, -95.235902, 3, ["misc"]),
  // restaurant · osm:node/2863476937
  sv("the-roost", "The Roost", 38.966627, -95.235307, 3, ["restaurant"]),
  // restaurant · osm:node/2156885368
  sv("the-salty-iguana", "The Salty Iguana", 38.970654, -95.308677, 3, ["restaurant"]),
  // pub · osm:node/2283112836
  sv("the-sandbar", "The Sandbar", 38.969389, -95.234999, 2, ["bar","downtown"]),
  // cafe · osm:node/9713230076
  sv("the-sconelady-s-coffee-shop", "The SconeLady's Coffee Shop", 38.957251, -95.277801, 3, ["cafe"]),
  // sports_centre · osm:node/2863458124
  sv("the-summit", "The Summit", 38.967341, -95.234706, 3, ["sports"]),
  // attraction · osm:way/1315560524
  sv("the-teepee-at-teepee-junction", "The Teepee at Teepee Junction", 39.000592, -95.231289, 3, ["misc"]),
  // post_office · osm:node/8193050003
  sv("the-ups-store", "The UPS Store", 38.928776, -95.259101, 3, ["misc"]),
  // post_office · osm:node/9279492842
  sv("the-ups-store-2", "The UPS Store", 38.944163, -95.281545, 3, ["misc"]),
  // post_office · osm:node/9691047539
  sv("the-ups-store-3", "The UPS Store", 38.972834, -95.288826, 3, ["misc"]),
  // theatre · osm:way/584945978
  sv("theatre-lawrence", "Theatre Lawrence", 38.973318, -95.302609, 3, ["venue"]),
  // department_store · osm:node/8019760616
  sv("tj-maxx", "TJ Maxx", 38.927099, -95.258939, 3, ["shopping"]),
  // restaurant · osm:node/12681478068
  sv("tokoyo-sushi", "Tokoyo Sushi", 38.976976, -95.233771, 3, ["restaurant"]),
  // restaurant · osm:node/8263027965
  sv("tokyo-steakhouse", "Tokyo Steakhouse", 38.970987, -95.283079, 3, ["restaurant"]),
  // bar · osm:node/2865488198
  sv("tonic-bar", "Tonic Bar", 38.970157, -95.235911, 3, ["bar"]),
  // restaurant · osm:node/12169333150
  sv("toppers-pizza", "Toppers Pizza", 38.963478, -95.244076, 3, ["restaurant"]),
  // restaurant · osm:node/8946030376
  sv("tortas-jalisco", "Tortas Jalisco", 38.967435, -95.262116, 3, ["restaurant"]),
  // bakery · osm:node/10821087345
  sv("tous-les-jours", "Tous les Jours", 38.973165, -95.30817, 3, ["misc"]),
  // hotel · osm:node/10127223779
  sv("town-place-suites-by-mariott", "Town Place Suites by Mariott", 38.967094, -95.234704, 3, ["hotel"]),
  // bicycle · osm:node/8201040240
  sv("trek", "Trek", 38.938225, -95.261703, 3, ["misc"]),
  // college · osm:node/11034665468
  sv("trinity-career-institute", "Trinity Career Institute", 38.948947, -95.235904, 3, ["campus"]),
  // place_of_worship · osm:way/174714176
  sv("trinity-episcopal-church", "Trinity Episcopal Church", 38.965245, -95.237681, 3, ["church"]),
  // fast_food · osm:node/8927835343
  sv("tropical-smoothie-cafe", "Tropical Smoothie Cafe", 38.935243, -95.259735, 3, ["restaurant"]),
  // hotel · osm:way/587878299
  sv("tru", "Tru", 38.973607, -95.305659, 3, ["hotel"]),
  // bank · osm:node/11740280911
  sv("truity-credit-union", "Truity Credit Union", 38.970267, -95.306147, 3, ["misc"]),
  // community_centre · osm:way/219195852
  sv("turnhalle-building", "Turnhalle Building", 38.967513, -95.23327, 3, ["misc"]),
  // university · osm:way/134809496
  sv("twente-hall", "Twente Hall", 38.956317, -95.243964, 3, ["misc"]),
  // restaurant · osm:node/11021349578
  sv("twisted-fresh", "Twisted Fresh", 38.970692, -95.309404, 3, ["restaurant"]),
  // bank · osm:node/1421128281
  sv("u-s-bank", "U.S. Bank", 38.967297, -95.235317, 3, ["misc"]),
  // memorial · osm:node/8929543992
  sv("u-s-navy-polaris-missile", "U.S. Navy Polaris Missile", 38.970283, -95.264504, 3, ["historic"]),
  // place_of_worship · osm:way/175354173
  sv("unity-of-lawrence", "Unity of Lawrence", 38.967769, -95.267588, 3, ["church"]),
  // place_of_worship · osm:way/219360527
  sv("university-community-of-christ", "University Community of Christ", 38.960659, -95.258907, 3, ["church"]),
  // university · osm:node/358648246
  sv("university-of-kansas-lawrence-campus-hambleton-h", "University of Kansas - Lawrence Campus Hambleton Hall", 38.948972, -95.2605, 3, ["campus"]),
  // university · osm:way/219360401
  sv("university-of-kansas-lawrence-campus-landscape-a", "University of Kansas - Lawrence Campus Landscape and Construction Building", 38.955255, -95.272079, 3, ["campus"]),
  // university · osm:node/358648323
  sv("university-of-kansas-lawrence-campus-moore-hall", "University of Kansas - Lawrence Campus Moore Hall", 38.949338, -95.261479, 3, ["campus"]),
  // university · osm:node/358648340
  sv("university-of-kansas-lawrence-campus-parker-hall", "University of Kansas - Lawrence Campus Parker Hall", 38.949114, -95.262604, 3, ["campus"]),
  // university · osm:way/266413490
  sv("university-press-offices", "University Press Offices", 38.956156, -95.269092, 3, ["misc"]),
  // university · osm:way/172183473
  sv("university-press-warehouse", "University Press Warehouse", 38.956221, -95.26901, 3, ["misc"]),
  // cafe · osm:node/9691047540
  sv("uplift-coffee-shop", "Uplift Coffee Shop", 38.972834, -95.288826, 3, ["cafe"]),
  // cafe · osm:node/11762571441
  sv("uplift-coffee-shop-2", "Uplift Coffee Shop", 38.981585, -95.235184, 3, ["cafe"]),
  // university · osm:way/219360421
  sv("vehicle-maintenance-shop", "Vehicle Maintenance Shop", 38.956958, -95.273094, 3, ["misc"]),
  // place_of_worship · osm:way/786058124
  sv("velocity-church", "Velocity Church", 38.972509, -95.290525, 3, ["church"]),
  // school · osm:node/10014159108
  sv("veritas-christian-school", "Veritas Christian School", 38.928119, -95.274828, 3, ["school"]),
  // park · osm:way/218263208
  sv("veterans-park", "Veterans Park", 38.950873, -95.240691, 3, ["park"]),
  // place_of_worship · osm:way/216267215
  sv("victory-bible-church", "Victory Bible Church", 38.948687, -95.235906, 3, ["church"]),
  // memorial · osm:node/6831704172
  sv("victory-eagle-wwi-memorial", "Victory Eagle-WWI Memorial", 38.95801, -95.245324, 3, ["historic"]),
  // memorial · osm:node/366762565
  sv("vietnam-war-memorial", "Vietnam War Memorial", 38.959516, -95.250798, 3, ["historic"]),
  // place_of_worship · osm:way/219196167
  sv("vintage-church", "Vintage Church", 38.957031, -95.235055, 3, ["church"]),
  // restaurant · osm:node/2864373494
  sv("wa-restaurant", "Wa Restaurant", 38.969712, -95.235911, 3, ["restaurant"]),
  // sports_centre · osm:way/87102559
  sv("wagnon-student-athletic-center", "Wagnon Student Athletic Center", 38.954733, -95.254032, 3, ["sports"]),
  // fast_food · osm:node/9279492840
  sv("wahlburgers", "Wahlburgers", 38.943978, -95.281007, 3, ["restaurant"]),
  // fire_station · osm:node/366764037
  sv("wakarusa-township-fire-department-station-2", "Wakarusa Township Fire Department Station 2", 39.000603, -95.272565, 3, ["misc"]),
  // park · osm:way/388802813
  sv("walnut-park", "Walnut Park", 38.975629, -95.231228, 3, ["park"]),
  // university · osm:way/172183474
  sv("warehouse", "Warehouse", 38.951973, -95.271928, 3, ["misc"]),
  // park · osm:way/389303828
  sv("water-tower-park", "Water Tower Park", 38.961574, -95.257588, 3, ["park"]),
  // university · osm:way/172183461
  sv("watkins-home", "Watkins Home", 38.955705, -95.244469, 3, ["misc"]),
  // museum · osm:way/217605648
  sv("watkins-museum-of-history", "Watkins Museum of History", 38.963943, -95.23652, 3, ["museum"]),
  // dormitory · osm:way/172183462
  sv("watkins-scholarship-hall", "Watkins Scholarship Hall", 38.956737, -95.242975, 3, ["dorm","campus"]),
  // library · osm:way/133939534
  sv("watson-library", "Watson Library", 38.956779, -95.244967, 3, ["library"]),
  // department_store · osm:node/2703830995
  sv("weaver-s", "Weaver's", 38.967512, -95.236238, 3, ["shopping"]),
  // fast_food · osm:node/8263027962
  sv("wendy-s", "Wendy's", 38.971312, -95.283288, 3, ["restaurant"]),
  // fast_food · osm:node/12535261171
  sv("wendy-s-2", "Wendy's", 38.959499, -95.243894, 3, ["restaurant"]),
  // university · osm:way/115429562
  sv("wescoe-hall", "Wescoe Hall", 38.957808, -95.247592, 3, ["misc"]),
  // university · osm:way/171147526
  sv("wesley-building-university-relations", "Wesley Building - University Relations", 38.959454, -95.242368, 3, ["misc"]),
  // bar · osm:node/8105173224
  sv("west-coast-saloon", "West Coast Saloon", 38.944387, -95.259877, 3, ["bar"]),
  // school · osm:way/966349612
  sv("west-middle-school", "West Middle School", 38.966311, -95.268973, 3, ["school"]),
  // place_of_worship · osm:way/175354172
  sv("west-side-presbyterian-church", "West Side Presbyterian Church", 38.965888, -95.280312, 3, ["church"]),
  // place_of_worship · osm:way/279546693
  sv("westwood-house", "Westwood House", 38.950046, -95.252378, 3, ["church"]),
  // restaurant · osm:node/2730653491
  sv("wild-pho", "Wild Pho", 38.964844, -95.235298, 3, ["restaurant"]),
  // fast_food · osm:node/9704445405
  sv("wingstop", "Wingstop", 38.943414, -95.242253, 3, ["restaurant"]),
  // university · osm:way/172577406
  sv("winona-hall", "Winona Hall", 38.939638, -95.23395, 3, ["misc"]),
  // school · osm:way/1187973426
  sv("woodlawn-elementary-school", "Woodlawn Elementary School", 38.976357, -95.228614, 3, ["school"]),
  // park · osm:way/1304577357
  sv("woody-park", "Woody Park", 38.980798, -95.247602, 3, ["park"]),
  // fitness_centre · osm:node/9758116135
  sv("yellow-brick-yoga", "Yellow Brick Yoga", 38.959261, -95.278279, 3, ["misc"]),
  // university · osm:way/32548161
  sv("youngberg-hall-center-for-research", "Youngberg Hall Center for Research", 38.951392, -95.265995, 3, ["misc"]),
  // cafe · osm:node/8702611627
  sv("z-s-divine-espresso", "Z's Divine Espresso", 38.943322, -95.212951, 3, ["cafe"]),
  // restaurant · osm:node/2283112838
  sv("zen-zero", "Zen Zero", 38.968999, -95.236192, 3, ["restaurant"]),
  // restaurant · osm:node/13726728660
  sv("zoe-s-noodle-house", "Zoe's Noodle House", 38.973661, -95.253718, 3, ["restaurant"]),
];
