/**
 * Regenerates supabase/migrations/0005_lock_submissions.sql from the current
 * location pool. The migration:
 *   1. Adds a `slug` column to locations
 *   2. Upserts every curated + vibe location with its slug (the client's
 *      location id)
 *   3. Creates submit_game() — a SECURITY DEFINER function that recomputes
 *      every round score server-side from the actual location coords and
 *      rejects the insert if any value disagrees with what the client sent
 *   4. Revokes anon INSERT on games; only the function can write
 *
 * Re-run any time the location pool changes:
 *   npx tsx scripts/build-lock-migration.ts
 */
import fs from "node:fs";
import { CURATED_LOCATIONS } from "../lib/curatedLocations";
import { VIBE_LOCATIONS } from "../lib/vibeLocations";
import { SCORE_DECAY_METERS, MAX_ROUND_SCORE } from "../lib/scoring";

const ALL = [...VIBE_LOCATIONS, ...CURATED_LOCATIONS];

// Dedupe by id (vibe wins over generated when ids collide — same rule as runtime)
const byId = new Map<string, (typeof ALL)[number]>();
for (const loc of ALL) if (!byId.has(loc.id)) byId.set(loc.id, loc);
const LOCATIONS = [...byId.values()];

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

const inserts = LOCATIONS.map(
  (l) =>
    `  ('${esc(l.name)}', '${esc(l.id)}', ${l.lat}, ${l.lng}, 'streetview', true)`,
).join(",\n");

const sql = `-- Auto-generated by scripts/build-lock-migration.ts.
-- Re-run that script if the curated location pool changes.

-- 1. slug column for stable lookup from the client (the runtime location id)
alter table public.locations
  add column if not exists slug text unique;

-- 2. Upsert every game-pool location. Existing rows are matched by name; the
--    slug is filled in (or rewritten if it has changed).
insert into public.locations (name, slug, lat, lng, type, active) values
${inserts}
on conflict (name) do update set
  slug = excluded.slug,
  lat = excluded.lat,
  lng = excluded.lng,
  type = excluded.type,
  active = excluded.active;

-- 3. Score validator. Recomputes the score for every round and rejects the
--    submission if the client lied. Score curve must stay in sync with
--    lib/scoring.ts.
--
--    SCORE_DECAY_METERS = ${SCORE_DECAY_METERS}
--    MAX_ROUND_SCORE    = ${MAX_ROUND_SCORE}
create or replace function public.submit_game(
  p_nickname text,
  p_mode text,
  p_daily_date date,
  p_total_score integer,
  p_rounds jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round jsonb;
  v_slug text;
  v_lat double precision;
  v_lng double precision;
  v_guess_lat double precision;
  v_guess_lng double precision;
  v_dist double precision;
  v_server_score integer;
  v_total integer := 0;
  v_today date := (now() at time zone 'America/Chicago')::date;
  v_id uuid;
begin
  if p_nickname is null or char_length(btrim(p_nickname)) < 1 or char_length(p_nickname) > 32 then
    raise exception 'invalid nickname';
  end if;
  if p_mode not in ('daily', 'freeplay') then
    raise exception 'invalid mode';
  end if;
  if p_mode = 'daily' and p_daily_date <> v_today then
    raise exception 'daily must use today''s date';
  end if;
  if jsonb_typeof(p_rounds) <> 'array' or jsonb_array_length(p_rounds) <> 5 then
    raise exception 'rounds must be an array of length 5';
  end if;

  for v_round in select * from jsonb_array_elements(p_rounds) loop
    v_slug := v_round->>'locationId';
    v_guess_lat := (v_round->>'guessLat')::double precision;
    v_guess_lng := (v_round->>'guessLng')::double precision;

    select lat, lng into v_lat, v_lng
      from public.locations
      where slug = v_slug and active = true;
    if not found then
      raise exception 'unknown location: %', v_slug;
    end if;

    -- Haversine in meters
    v_dist := 6371000 * 2 * asin(sqrt(
      power(sin(radians((v_lat - v_guess_lat) / 2)), 2)
      + cos(radians(v_lat)) * cos(radians(v_guess_lat))
      * power(sin(radians((v_lng - v_guess_lng) / 2)), 2)
    ));

    -- Score curve — must match lib/scoring.ts
    v_server_score := round(${MAX_ROUND_SCORE} * exp(-v_dist / ${SCORE_DECAY_METERS}));
    if v_server_score < 0 then v_server_score := 0; end if;

    -- Allow 2-point tolerance for floating-point rounding diffs between JS
    -- and Postgres
    if abs(v_server_score - (v_round->>'score')::integer) > 2 then
      raise exception 'round score mismatch (claimed %, server %, slug %)',
        (v_round->>'score')::integer, v_server_score, v_slug;
    end if;

    v_total := v_total + v_server_score;
  end loop;

  if abs(v_total - p_total_score) > 5 then
    raise exception 'total score mismatch (claimed %, server %)', p_total_score, v_total;
  end if;

  insert into public.games
    (player_nickname, mode, daily_date, total_score, rounds)
    values (btrim(p_nickname), p_mode, p_daily_date, v_total, p_rounds)
    returning id into v_id;
  return v_id;
end;
$$;

-- 4. Lock the games table — only the validator can write
drop policy if exists games_insert_self on public.games;
revoke insert on public.games from anon, authenticated;

grant execute on function public.submit_game(text, text, date, integer, jsonb)
  to anon, authenticated;
`;

fs.writeFileSync("supabase/migrations/0005_lock_submissions.sql", sql);
console.log(
  `→ wrote supabase/migrations/0005_lock_submissions.sql (${LOCATIONS.length} locations, ${sql.length} bytes)`,
);
