-- Auto-generated by scripts/build-lock-migration.ts.
-- Re-run that script if the curated location pool changes.

-- 1. slug column for stable lookup from the client (the runtime location id)
alter table public.locations
  add column if not exists slug text unique;

-- 2. Upsert every game-pool location. Existing rows are matched by name; the
--    slug is filled in (or rewritten if it has changed).
insert into public.locations (name, slug, lat, lng, type, active) values
  ('Mass St, 600 block', 'vibe-mass-600', 38.9692, -95.2353, 'streetview', true),
  ('Mass St, 700 block', 'vibe-mass-700', 38.9704, -95.2353, 'streetview', true),
  ('Mass St, 800 block', 'vibe-mass-800', 38.9712, -95.2353, 'streetview', true),
  ('Mass St, 900 block', 'vibe-mass-900', 38.972, -95.2353, 'streetview', true),
  ('Mass St, 1000 block', 'vibe-mass-1000', 38.9728, -95.2353, 'streetview', true),
  ('Mass St, 1100 block', 'vibe-mass-1100', 38.9736, -95.2353, 'streetview', true),
  ('23rd & Iowa', 'vibe-23rd-iowa', 38.9417, -95.2496, 'streetview', true),
  ('23rd & Louisiana', 'vibe-23rd-louisiana', 38.942, -95.2438, 'streetview', true),
  ('23rd & Naismith', 'vibe-23rd-naismith', 38.9418, -95.2526, 'streetview', true),
  ('23rd & Mass', 'vibe-23rd-mass', 38.9418, -95.2357, 'streetview', true),
  ('6th & Iowa', 'vibe-6th-iowa', 38.9712, -95.2496, 'streetview', true),
  ('6th & Wakarusa', 'vibe-6th-wakarusa', 38.9719, -95.3083, 'streetview', true),
  ('6th & Mass', 'vibe-6th-mass', 38.9696, -95.2353, 'streetview', true),
  ('9th & Mass', 'vibe-9th-mass', 38.972, -95.2353, 'streetview', true),
  ('11th & Mass', 'vibe-11th-mass', 38.9736, -95.2353, 'streetview', true),
  ('Bob Billings & Kasold roundabout', 'vibe-bob-billings', 38.9577, -95.2752, 'streetview', true),
  ('Mt. Oread summit (The Hill)', 'vibe-hill-summit', 38.9577, -95.2487, 'streetview', true),
  ('Wescoe Beach', 'vibe-wescoe-beach', 38.9577, -95.247, 'streetview', true),
  ('Jayhawk Blvd, mid-campus', 'vibe-jayhawk-blvd', 38.9582, -95.247, 'streetview', true),
  ('Daisy Hill (overlook)', 'vibe-daisy-hill', 38.9618, -95.2519, 'streetview', true),
  ('Mass St bridge over the Kaw', 'vibe-mass-bridge', 38.9772, -95.2353, 'streetview', true),
  ('Iowa St bridge over the Kaw', 'vibe-iowa-bridge', 38.9783, -95.2497, 'streetview', true),
  ('Bullwinkle''s (1344 Tennessee)', 'vibe-bullwinkles', 38.9582, -95.2412, 'streetview', true),
  ('The Wagon Wheel Cafe (507 W 14th)', 'vibe-wagon-wheel', 38.9555, -95.248, 'streetview', true),
  ('The Yacht Club (530 Wisconsin)', 'vibe-yacht-club', 38.9695, -95.2393, 'streetview', true),
  ('Slow Ride Roadhouse', 'vibe-slow-ride', 38.942, -95.2493, 'streetview', true),
  ('Wonder Fair (803 1/2 Mass)', 'vibe-wonder-fair', 38.9712, -95.2353, 'streetview', true),
  ('Wheatfields Bakery & Cafe (904 Vermont)', 'vibe-wheatfields', 38.972, -95.237, 'streetview', true),
  ('Bowersock Dam', 'vibe-bowersock', 38.9762, -95.2333, 'streetview', true),
  ('Hy-Vee (4000 W 6th)', 'vibe-hyvee-6th', 38.9719, -95.2792, 'streetview', true),
  ('Hy-Vee (3504 Clinton Pkwy)', 'vibe-hyvee-clinton', 38.945, -95.264, 'streetview', true),
  ('Dillons (23rd & Louisiana)', 'vibe-dillons-23rd', 38.942, -95.2438, 'streetview', true),
  ('Dillons (6th & Monterey Way)', 'vibe-dillons-6th', 38.9714, -95.2615, 'streetview', true),
  ('Lawrence High School (1901 Louisiana)', 'vibe-lawrence-high', 38.9494, -95.2437, 'streetview', true),
  ('Tellers Restaurant (746 Mass)', 'vibe-tellers', 38.9709, -95.2353, 'streetview', true),
  ('Quinton''s Bar & Deli (615 Mass)', 'vibe-quintons', 38.9695, -95.2353, 'streetview', true),
  ('23rd Street Brewery (3512 Clinton Pkwy)', 'vibe-23rd-brewery', 38.945, -95.262, 'streetview', true),
  ('Henry''s Coffee Shop (downtown)', 'vibe-henrys', 38.9712, -95.2354, 'streetview', true),
  ('The Merc Co-op (downtown)', 'vibe-the-merc', 38.9686, -95.238, 'streetview', true),
  ('The Hawk (1340 Ohio)', 'vibe-the-hawk', 38.9582, -95.244, 'streetview', true),
  ('Logies (Mass St)', 'vibe-logies', 38.972, -95.2353, 'streetview', true),
  ('Sigma Alpha Epsilon (1301 Tennessee)', 'vibe-frat-sae', 38.9585, -95.2412, 'streetview', true),
  ('Lambda Chi Alpha (1340 Tennessee)', 'vibe-frat-lambda-chi', 38.9582, -95.2412, 'streetview', true),
  ('Pi Kappa Alpha (1414 Tennessee)', 'vibe-frat-pike', 38.9576, -95.2412, 'streetview', true),
  ('Beta Theta Pi (1425 Tennessee)', 'vibe-frat-beta', 38.9575, -95.2412, 'streetview', true),
  ('Sigma Chi (1439 Tennessee)', 'vibe-frat-sigma-chi', 38.9573, -95.2412, 'streetview', true),
  ('Sigma Nu (1501 Tennessee)', 'vibe-frat-sigma-nu', 38.9568, -95.2412, 'streetview', true),
  ('Theta Chi (1502 Tennessee)', 'vibe-frat-theta-chi', 38.9568, -95.2412, 'streetview', true),
  ('Phi Gamma Delta — FIJI (1545 Tennessee)', 'vibe-frat-fiji', 38.9564, -95.2412, 'streetview', true),
  ('Sigma Phi Epsilon (1645 Tennessee)', 'vibe-frat-sigep', 38.9555, -95.2412, 'streetview', true),
  ('Phi Delta Theta (1621 Edgehill)', 'vibe-frat-phi-delt', 38.9558, -95.2403, 'streetview', true),
  ('Phi Kappa Psi (1100 Indiana)', 'vibe-frat-phi-psi', 38.9602, -95.2454, 'streetview', true),
  ('Delta Upsilon (1025 Mississippi)', 'vibe-frat-du', 38.9608, -95.2418, 'streetview', true),
  ('Delta Tau Delta (1111 W 11th)', 'vibe-frat-delt', 38.96, -95.247, 'streetview', true),
  ('Decade Coffee (920 Mass)', 'vibe-decade', 38.972, -95.2353, 'streetview', true),
  ('Cottin''s Hardware (1832 Mass)', 'vibe-cottins', 38.955, -95.2353, 'streetview', true),
  ('Dempsey''s Burger Pub (623 Vermont)', 'vibe-dempseys', 38.9697, -95.237, 'streetview', true),
  ('Mirth Cafe (745 New Hampshire)', 'vibe-mirth', 38.9708, -95.2342, 'streetview', true),
  ('Maceli''s Banquet Hall (1031 New Hampshire)', 'vibe-maceli', 38.9724, -95.2342, 'streetview', true),
  ('Pachamama''s (800 New Hampshire)', 'vibe-pachamama', 38.9711, -95.2342, 'streetview', true),
  ('Wakarusa Brewing Co (west Lawrence)', 'vibe-wakarusa-brewing', 38.9446, -95.279, 'streetview', true),
  ('Aimee''s Coffeehouse (1025 Mass)', 'vibe-aimees', 38.9728, -95.2353, 'streetview', true),
  ('Liberty Hall', 'liberty-hall', 38.971441, -95.235914, 'streetview', true),
  ('The Bottleneck', 'the-bottleneck', 38.969846, -95.236534, 'streetview', true),
  ('Allen Fieldhouse', 'allen-fieldhouse', 38.954612, -95.252377, 'streetview', true),
  ('David Booth Kansas Memorial Stadium', 'david-booth-kansas-memorial-stadium', 38.962869, -95.24636, 'streetview', true),
  ('The Granada', 'the-granada', 38.964742, -95.235903, 'streetview', true),
  ('The Jayhawker at The Eldridge', 'the-jayhawker-at-the-eldridge', 38.971254, -95.236202, 'streetview', true),
  ('Johnny''s Tavern', 'johnny-s-tavern', 38.969356, -95.308082, 'streetview', true),
  ('The Eldridge Hotel', 'the-eldridge-hotel', 38.971085, -95.236542, 'streetview', true),
  ('Memorial Campanile & Carillon', 'memorial-campanile-carillon', 38.960003, -95.246937, 'streetview', true),
  ('The Oread', 'the-oread', 38.962343, -95.242906, 'streetview', true),
  ('Replay Lounge', 'replay-lounge', 38.965813, -95.235902, 'streetview', true),
  ('The Sandbar', 'the-sandbar', 38.969389, -95.234999, 'streetview', true),
  ('Battenfeld Scholarship Hall', 'battenfeld-scholarship-hall', 38.957247, -95.243066, 'streetview', true),
  ('Lied Center of Kansas', 'lied-center-of-kansas', 38.954422, -95.262803, 'streetview', true),
  ('Spencer Museum of Art', 'spencer-museum-of-art', 38.959666, -95.244328, 'streetview', true),
  ('Watkins Museum of History', 'watkins-museum-of-history', 38.963943, -95.23652, 'streetview', true),
  ('Douthart Scholarship Hall', 'douthart-scholarship-hall', 38.958426, -95.241704, 'streetview', true),
  ('Sellards Scholarship Hall', 'sellards-scholarship-hall', 38.956489, -95.241587, 'streetview', true),
  ('Stephenson Scholarship Hall', 'stephenson-scholarship-hall', 38.957779, -95.242132, 'streetview', true),
  ('The Bourgeois Pig', 'the-bourgeois-pig', 38.967601, -95.23532, 'streetview', true),
  ('Kenneth Spencer Research Library', 'kenneth-spencer-research-library', 38.959416, -95.247818, 'streetview', true),
  ('Lawrence Public Library', 'lawrence-public-library', 38.970817, -95.237628, 'streetview', true),
  ('Watson Library', 'watson-library', 38.956779, -95.244967, 'streetview', true),
  ('Ellsworth Residential Hall', 'ellsworth-residential-hall', 38.952747, -95.259197, 'streetview', true),
  ('Hashinger Residence Hall', 'hashinger-residence-hall', 38.954127, -95.259158, 'streetview', true),
  ('Hoglund Ballpark', 'hoglund-ballpark', 38.952892, -95.252759, 'streetview', true),
  ('Naismith Hall', 'naismith-hall', 38.950764, -95.250806, 'streetview', true),
  ('Rock Chalk Park', 'rock-chalk-park', 38.981179, -95.32859, 'streetview', true),
  ('Templin Residence Hall', 'templin-residence-hall', 38.956386, -95.25838, 'streetview', true),
  ('Ambler Student Recreation Fitness Center', 'ambler-student-recreation-fitness-center', 38.952637, -95.248068, 'streetview', true),
  ('Anderson Family Strength and Conditioning Center', 'anderson-family-strength-and-conditioning-center', 38.954215, -95.255464, 'streetview', true),
  ('Corbin Residence Hall', 'corbin-residence-hall', 38.964529, -95.241448, 'streetview', true),
  ('Free State High School', 'free-state-high-school', 38.976347, -95.304642, 'streetview', true),
  ('Gertrude Sellards Pearson Residence Hall', 'gertrude-sellards-pearson-residence-hall', 38.964922, -95.241743, 'streetview', true),
  ('Kansas Union', 'kansas-union', 38.959382, -95.243212, 'streetview', true),
  ('Love Garden Sounds', 'love-garden-sounds', 38.968453, -95.235856, 'streetview', true),
  ('Strong Hall', 'strong-hall', 38.958383, -95.247763, 'streetview', true),
  ('The Burger Stand at The Casbah', 'the-burger-stand-at-the-casbah', 38.96939, -95.236182, 'streetview', true),
  ('Wescoe Hall', 'wescoe-hall', 38.957808, -95.247592, 'streetview', true),
  ('Bishop Seabury Academy', 'bishop-seabury-academy', 38.943191, -95.29322, 'streetview', true),
  ('Budig Hall', 'budig-hall', 38.958013, -95.24965, 'streetview', true),
  ('Capitol Federal Hall', 'capitol-federal-hall', 38.953697, -95.250156, 'streetview', true),
  ('Lawrence Arts Center', 'lawrence-arts-center', 38.966487, -95.234137, 'streetview', true),
  ('Marvin Hall', 'marvin-hall', 38.958241, -95.25024, 'streetview', true),
  ('Robert J. Dole Institute of Politics', 'robert-j-dole-institute-of-politics', 38.955876, -95.264937, 'streetview', true),
  ('Snow Hall', 'snow-hall', 38.958981, -95.249107, 'streetview', true),
  ('715 Restaurant', '715-restaurant', 38.970611, -95.235912, 'streetview', true),
  ('Adams Alumni Center', 'adams-alumni-center', 38.960452, -95.242319, 'streetview', true),
  ('Bailey Hall', 'bailey-hall', 38.957868, -95.246281, 'streetview', true),
  ('Blake Hall', 'blake-hall', 38.956276, -95.243588, 'streetview', true),
  ('Henry''s pub and coffee house', 'henry-s-pub-and-coffee-house', 38.969262, -95.235306, 'streetview', true),
  ('Jefferson''s', 'jefferson-s', 38.955325, -95.30652, 'streetview', true),
  ('Jefferson''s Lawrence', 'jefferson-s-lawrence', 38.969712, -95.235911, 'streetview', true),
  ('La Prima Tazza', 'la-prima-tazza', 38.97155, -95.235911, 'streetview', true),
  ('Lindley Hall', 'lindley-hall', 38.958433, -95.25115, 'streetview', true),
  ('Lippincott Hall', 'lippincott-hall', 38.958096, -95.243992, 'streetview', true),
  ('Summerfield Hall', 'summerfield-hall', 38.955781, -95.249665, 'streetview', true),
  ('The Burge Union', 'the-burge-union', 38.955089, -95.254941, 'streetview', true),
  ('Grace Pearson Scholarship Hall', 'grace-pearson-scholarship-hall', 38.958798, -95.241703, 'streetview', true),
  ('Joseph R Pearson Hall', 'joseph-r-pearson-hall', 38.962431, -95.250866, 'streetview', true),
  ('K.K. Amini Scholarship Hall', 'k-k-amini-scholarship-hall', 38.95889, -95.241703, 'streetview', true),
  ('Krehbiel Scholarship Hall', 'krehbiel-scholarship-hall', 38.959692, -95.241167, 'streetview', true),
  ('Limestone Pizza•Kitchen•Bar', 'limestone-pizza-kitchen-bar', 38.968774, -95.235902, 'streetview', true),
  ('Local Burger', 'local-burger', 38.970534, -95.237123, 'streetview', true),
  ('Margaret Amini Scholarship Hall', 'margaret-amini-scholarship-hall', 38.959256, -95.241703, 'streetview', true),
  ('Miller Scholarship Hall', 'miller-scholarship-hall', 38.956446, -95.242793, 'streetview', true),
  ('Pearson Scholarship Hall', 'pearson-scholarship-hall', 38.957237, -95.242188, 'streetview', true),
  ('Rieger Scholarship Hall', 'rieger-scholarship-hall', 38.95896, -95.241162, 'streetview', true),
  ('The Salty Iguana', 'the-salty-iguana', 38.970654, -95.308677, 'streetview', true),
  ('Watkins Scholarship Hall', 'watkins-scholarship-hall', 38.956737, -95.242975, 'streetview', true),
  ('Oread Center', 'oread-center', 38.966992, -95.24522, 'streetview', true),
  ('Oread Friends Meeting', 'oread-friends-meeting', 38.962103, -95.225447, 'streetview', true),
  ('The Jayhawk Nest', 'the-jayhawk-nest', 38.959267, -95.243268, 'streetview', true),
  ('Booth Family Hall of Athletics', 'booth-family-hall-of-athletics', 38.954333, -95.25226, 'streetview', true),
  ('Chesty Lion', 'chesty-lion', 38.950111, -95.243283, 'streetview', true),
  ('Crafton-Preyer Theatre', 'crafton-preyer-theatre', 38.956496, -95.251966, 'streetview', true),
  ('Haskell Cultural Center and Museum', 'haskell-cultural-center-and-museum', 38.940328, -95.233187, 'streetview', true),
  ('Jayhawk Towers Apartments', 'jayhawk-towers-apartments', 38.957043, -95.255772, 'streetview', true),
  ('MacKomics Studio', 'mackomics-studio', 38.944329, -95.239414, 'streetview', true),
  ('Moses', 'moses', 38.959672, -95.242652, 'streetview', true),
  ('Natural History Museum', 'natural-history-museum', 38.958748, -95.243532, 'streetview', true),
  ('Prairie Park Nature Center', 'prairie-park-nature-center', 38.933124, -95.215798, 'streetview', true),
  ('Regal Southwind', 'regal-southwind', 38.921533, -95.263382, 'streetview', true),
  ('Relay Race', 'relay-race', 38.976164, -95.304641, 'streetview', true),
  ('Theatre Lawrence', 'theatre-lawrence', 38.973318, -95.302609, 'streetview', true),
  ('Astros Billiards and Bar', 'astros-billiards-and-bar', 38.970987, -95.283079, 'streetview', true),
  ('Blade & Timber Axe Throwing', 'blade-timber-axe-throwing', 38.970335, -95.235912, 'streetview', true),
  ('Crimson and Brews', 'crimson-and-brews', 38.967266, -95.263295, 'streetview', true),
  ('Downs Residence Hall', 'downs-residence-hall', 38.951283, -95.253559, 'streetview', true),
  ('Elmo''s Tavern', 'elmo-s-tavern', 38.977823, -95.228266, 'streetview', true),
  ('Empire Pubcade and Venue', 'empire-pubcade-and-venue', 38.967573, -95.262548, 'streetview', true),
  ('Five Bar', 'five-bar', 38.965784, -95.236045, 'streetview', true),
  ('Harolds', 'harolds', 38.966749, -95.235901, 'streetview', true),
  ('HOOKAH LOUNGE', 'hookah-lounge', 38.964742, -95.235903, 'streetview', true),
  ('Lawrence Beer Company', 'lawrence-beer-company', 38.968402, -95.228906, 'streetview', true),
  ('Lawrence Beer Company', 'lawrence-beer-company-2', 38.956628, -95.305074, 'streetview', true),
  ('Leroy''s Tavern', 'leroy-s-tavern', 38.970352, -95.23495, 'streetview', true),
  ('Lewis Residence Hall', 'lewis-residence-hall', 38.955304, -95.258245, 'streetview', true),
  ('Local', 'local', 38.972476, -95.235913, 'streetview', true),
  ('Lucia', 'lucia', 38.964924, -95.235903, 'streetview', true),
  ('Mr. Brew''s Taphouse', 'mr-brew-s-taphouse-2', 38.925818, -95.259618, 'streetview', true),
  ('Northside Social', 'northside-social', 38.977822, -95.229361, 'streetview', true),
  ('Oswald Residence Hall', 'oswald-residence-hall', 38.954279, -95.259994, 'streetview', true),
  ('Red Lyon Tavern', 'red-lyon-tavern', 38.965907, -95.235902, 'streetview', true),
  ('Rick''s Place', 'rick-s-place', 38.967776, -95.24495, 'streetview', true),
  ('Self Residence Hall', 'self-residence-hall', 38.955551, -95.259325, 'streetview', true),
  ('Shenago Lounge', 'shenago-lounge', 38.956082, -95.305811, 'streetview', true),
  ('The Eighth Street Tap Room', 'the-eighth-street-tap-room', 38.969388, -95.234884, 'streetview', true),
  ('Tonic Bar', 'tonic-bar', 38.970157, -95.235911, 'streetview', true),
  ('West Coast Saloon', 'west-coast-saloon', 38.944387, -95.259877, 'streetview', true),
  ('Anschutz Sports Pavilion', 'anschutz-sports-pavilion', 38.953973, -95.255365, 'streetview', true),
  ('Breezedale', 'breezedale', 38.942705, -95.235908, 'streetview', true),
  ('Coffin Sports Complex', 'coffin-sports-complex', 38.939265, -95.228356, 'streetview', true),
  ('Core:form Studio', 'core-form-studio', 38.96769, -95.230655, 'streetview', true),
  ('Country Inn & Suites', 'country-inn-suites', 38.942993, -95.207975, 'streetview', true),
  ('D-BAT Baseball and Softball Academy', 'd-bat-baseball-and-softball-academy', 38.939886, -95.199116, 'streetview', true),
  ('DoubleTree', 'doubletree', 38.979974, -95.257525, 'streetview', true),
  ('Douglas County Courthouse', 'douglas-county-courthouse', 38.963418, -95.2359, 'streetview', true),
  ('Douglas County Memorial of Honor', 'douglas-county-memorial-of-honor', 38.978216, -95.234434, 'streetview', true),
  ('East Lawrence Recreation Center', 'east-lawrence-recreation-center', 38.956467, -95.220092, 'streetview', true),
  ('Foley Hall', 'foley-hall', 38.948076, -95.263336, 'streetview', true),
  ('General John Roberts Castle', 'general-john-roberts-castle', 38.95965, -95.236519, 'streetview', true),
  ('Grover Barn Underground Railroad Station', 'grover-barn-underground-railroad-station', 38.941504, -95.269423, 'streetview', true),
  ('Haskell Library', 'haskell-library', 38.939153, -95.233815, 'streetview', true),
  ('Haskell Stadium', 'haskell-stadium', 38.940015, -95.230611, 'streetview', true),
  ('Higuchi Hall', 'higuchi-hall', 38.946268, -95.262587, 'streetview', true),
  ('Holcom Park Recreation Center', 'holcom-park-recreation-center', 38.935562, -95.268225, 'streetview', true),
  ('Horejsi Family Athletics Center', 'horejsi-family-athletics-center', 38.953707, -95.253326, 'streetview', true)
on conflict (name) do update set
  slug = excluded.slug,
  lat = excluded.lat,
  lng = excluded.lng,
  type = excluded.type,
  active = excluded.active;

-- 3. Score validator. Recomputes the score for every round and rejects the
--    submission if the client lied. Score curve must stay in sync with
--    lib/scoring.ts.
--
--    SCORE_DECAY_METERS = 500
--    MAX_ROUND_SCORE    = 5000
create or replace function public.submit_game(
  p_nickname text,
  p_mode text,
  p_daily_date date,
  p_total_score integer,
  p_rounds jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round jsonb;
  v_slug text;
  v_lat double precision;
  v_lng double precision;
  v_guess_lat double precision;
  v_guess_lng double precision;
  v_dist double precision;
  v_server_score integer;
  v_total integer := 0;
  v_today date := (now() at time zone 'America/Chicago')::date;
  v_id uuid;
begin
  if p_nickname is null or char_length(btrim(p_nickname)) < 1 or char_length(p_nickname) > 32 then
    raise exception 'invalid nickname';
  end if;
  if p_mode not in ('daily', 'freeplay') then
    raise exception 'invalid mode';
  end if;
  if p_mode = 'daily' and p_daily_date <> v_today then
    raise exception 'daily must use today''s date';
  end if;
  if jsonb_typeof(p_rounds) <> 'array' or jsonb_array_length(p_rounds) <> 5 then
    raise exception 'rounds must be an array of length 5';
  end if;

  for v_round in select * from jsonb_array_elements(p_rounds) loop
    v_slug := v_round->>'locationId';
    v_guess_lat := (v_round->>'guessLat')::double precision;
    v_guess_lng := (v_round->>'guessLng')::double precision;

    select lat, lng into v_lat, v_lng
      from public.locations
      where slug = v_slug and active = true;
    if not found then
      raise exception 'unknown location: %', v_slug;
    end if;

    -- Haversine in meters
    v_dist := 6371000 * 2 * asin(sqrt(
      power(sin(radians((v_lat - v_guess_lat) / 2)), 2)
      + cos(radians(v_lat)) * cos(radians(v_guess_lat))
      * power(sin(radians((v_lng - v_guess_lng) / 2)), 2)
    ));

    -- Score curve — must match lib/scoring.ts
    v_server_score := round(5000 * exp(-v_dist / 500));
    if v_server_score < 0 then v_server_score := 0; end if;

    -- Allow 2-point tolerance for floating-point rounding diffs between JS
    -- and Postgres
    if abs(v_server_score - (v_round->>'score')::integer) > 2 then
      raise exception 'round score mismatch (claimed %, server %, slug %)',
        (v_round->>'score')::integer, v_server_score, v_slug;
    end if;

    v_total := v_total + v_server_score;
  end loop;

  if abs(v_total - p_total_score) > 5 then
    raise exception 'total score mismatch (claimed %, server %)', p_total_score, v_total;
  end if;

  insert into public.games
    (player_nickname, mode, daily_date, total_score, rounds)
    values (btrim(p_nickname), p_mode, p_daily_date, v_total, p_rounds)
    returning id into v_id;
  return v_id;
end;
$$;

-- 4. Lock the games table — only the validator can write
drop policy if exists games_insert_self on public.games;
revoke insert on public.games from anon, authenticated;

grant execute on function public.submit_game(text, text, date, integer, jsonb)
  to anon, authenticated;
